msgid ""
msgstr ""
"Project-Id-Version: ubuntu-translations\n"
"Report-Msgid-Bugs-To: FULL NAME <EMAIL@ADDRESS>\n"
"POT-Creation-Date: 2008-03-31 17:40+0100\n"
"PO-Revision-Date: 2025-01-13 12:55\n"
"Last-Translator: \n"
"Language-Team: Ukrainian\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2025-01-09 07:56+0000\n"
"X-Generator: Launchpad (build 6394e03793719e8d73f5a60b5439440e693c92f1)\n"
"Plural-Forms: nplurals=4; plural=((n%10==1 && n%100!=11) ? 0 : ((n%10 >= 2 && n%10 <=4 && (n%100 < 12 || n%100 > 14)) ? 1 : ((n%10 == 0 || (n%10 >= 5 && n%10 <=9)) || (n%100 >= 11 && n%100 <= 14)) ? 2 : 3));\n"
"X-Crowdin-Project: ubuntu-translations\n"
"X-Crowdin-Project-ID: 485161\n"
"X-Crowdin-Language: uk\n"
"X-Crowdin-File: /main/noble/en_GB/po-xen_xen-xm-be.po\n"
"X-Crowdin-File-ID: 703\n"
"Language: uk_UA\n"

#: xen/xm/XenAPI.py:58
#, python-format
msgid "Internal error: %(1)s."
msgstr ""

#: xen/xm/XenAPI.py:59
#, python-format
msgid "This map already contains %(1)s -> %(2)s."
msgstr ""

#: xen/xm/XenAPI.py:60
#, python-format
msgid "The method %(1)s is unsupported."
msgstr ""

#: xen/xm/XenAPI.py:61
#, python-format
msgid "The method %(1)s takes %(2)s argument(s) (%(3)s given)."
msgstr ""

#: xen/xm/XenAPI.py:62
msgid "Permission denied."
msgstr ""

#: xen/xm/XenAPI.py:63
#, python-format
msgid "Value \"%(2)s\" for %(1)s is not supported by this server.  The server said \"%(3)s\"."
msgstr ""

#: xen/xm/XenAPI.py:64
#, python-format
msgid "The %(1)s handle %(2)s is invalid."
msgstr ""

#: xen/xm/XenAPI.py:65
msgid "You attempted an operation that was not allowed."
msgstr ""

#: xen/xm/XenAPI.py:66
msgid "The network you specified already has a PIF attached to it, and so another one may not be attached."
msgstr ""

#: xen/xm/XenAPI.py:67
#, python-format
msgid "%(2)s"
msgstr ""

