msgid ""
msgstr ""
"Project-Id-Version: ubuntu-translations\n"
"Report-Msgid-Bugs-To: sebastian.heinlein@web.de\n"
"POT-Creation-Date: 2024-10-02 14:18+0000\n"
"PO-Revision-Date: 2025-03-24 16:51\n"
"Last-Translator: Ubuntu Belarusian Translators Team <Unknown>\n"
"Language-Team: Russian\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=4; plural=((n%10==1 && n%100!=11) ? 0 : ((n%10 >= 2 && n%10 <=4 && (n%100 < 12 || n%100 > 14)) ? 1 : ((n%10 == 0 || (n%10 >= 5 && n%10 <=9)) || (n%100 >= 11 && n%100 <= 14)) ? 2 : 3));\n"
"X-Launchpad-Export-Date: 2025-03-21 06:16+0000\n"
"X-Generator: Launchpad (build aa29ae0fff49e4e804b39147c9f259d2fb023199)\n"
"X-Crowdin-File: /main/noble/en_GB/po-update-manager_update-manager-be.po\n"
"X-Crowdin-Language: ru\n"
"X-Crowdin-Project: ubuntu-translations\n"
"X-Crowdin-Project-ID: 485161\n"
"X-Crowdin-File-ID: 31\n"
"Language: ru_RU\n"

#: ../UpdateManager/backend/InstallBackendAptdaemon.py:155
msgid "Checking for updates…"
msgstr ""

#: ../UpdateManager/backend/InstallBackendAptdaemon.py:217
#: ../UpdateManager/backend/InstallBackendAptdaemon.py:291
#: ../UpdateManager/backend/InstallBackendAptdaemon.py:341
msgid "Installing updates…"
msgstr ""

#: ../UpdateManager/backend/InstallBackendSynaptic.py:43
msgid "Please wait, this can take some time."
msgstr ""

#: ../UpdateManager/backend/InstallBackendSynaptic.py:45
msgid "Update is complete"
msgstr ""

#: ../UpdateManager/backend/__init__.py:300
msgid "Updating snaps"
msgstr ""

#: ../UpdateManager/backend/__init__.py:328
#, python-format
msgid "Refreshing %s snap"
msgstr ""

#: ../UpdateManager/backend/__init__.py:336
#, python-format
msgid "Removing %s snap"
msgstr ""

#: ../UpdateManager/backend/__init__.py:343
#, python-format
msgid "Installing %s snap"
msgstr ""

#: ../UpdateManager/backend/__init__.py:356
msgid "Upgrade only partially completed."
msgstr ""

#: ../UpdateManager/backend/__init__.py:358
msgid "An error occurred while updating snaps. Please check your network connection."
msgstr ""

#: ../UpdateManager/ChangelogViewer.py:82
msgid "Open Link in Browser"
msgstr ""

#: ../UpdateManager/ChangelogViewer.py:87
msgid "Copy Link to Clipboard"
msgstr ""

#: ../UpdateManager/Dialogs.py:128
msgid "Settings…"
msgstr ""

#: ../UpdateManager/Dialogs.py:169
msgid "<b>Tip:</b> You can use Livepatch with Ubuntu Pro to keep your computer more secure between restarts."
msgstr ""

#: ../UpdateManager/Dialogs.py:174
msgid "Settings & Pro…"
msgstr ""

#: ../UpdateManager/Dialogs.py:189
#, python-format
msgid "%d Livepatch update applied since the last restart."
msgid_plural "%d Livepatch updates applied since the last restart."
msgstr[0] ""
msgstr[1] ""
msgstr[2] ""
msgstr[3] ""

#: ../UpdateManager/Dialogs.py:197
#, python-format
msgid "%d Livepatch update failed to apply since the last restart."
msgid_plural "%d Livepatch updates failed to apply since the last restart."
msgstr[0] ""
msgstr[1] ""
msgstr[2] ""
msgstr[3] ""

#: ../UpdateManager/Dialogs.py:220 ../UpdateManager/UpdateManager.py:435
msgid "You stopped the check for updates."
msgstr ""

#: ../UpdateManager/Dialogs.py:222
msgid "_Check Again"
msgstr ""

#: ../UpdateManager/Dialogs.py:235
msgid "No software updates are available."
msgstr ""

#: ../UpdateManager/Dialogs.py:237 ../UpdateManager/Dialogs.py:249
msgid "The software on this computer is up to date."
msgstr ""

#: ../UpdateManager/Dialogs.py:252
#, python-format
msgid "However, %s %s is now available (you have %s)."
msgstr ""

#: ../UpdateManager/Dialogs.py:260
msgid "Upgrade…"
msgstr ""

#: ../UpdateManager/Dialogs.py:286
msgid "New important security and hardware support update."
msgstr ""

#: ../UpdateManager/Dialogs.py:295
msgid "_Install…"
msgstr ""

#: ../UpdateManager/Dialogs.py:309
#, python-format
msgid "Software updates are no longer provided for %s %s."
msgstr ""

#: ../UpdateManager/Dialogs.py:314
#, python-format
msgid "To stay secure, you should upgrade to %s %s."
msgstr ""

#: ../UpdateManager/Dialogs.py:327
msgid "Sorry, there are no more upgrades for this system"
msgstr ""

#: ../UpdateManager/Dialogs.py:331
#, python-format
msgid "\n"
"There will not be any further Ubuntu releases for this system's '%s' architecture.\n\n"
"Updates for Ubuntu %s will continue until 2023-04-26.\n\n"
"If you reinstall Ubuntu from ubuntu.com/download, future upgrades will be available."
msgstr ""

#: ../UpdateManager/Dialogs.py:347
msgid "Not all updates can be installed"
msgstr ""

#: ../UpdateManager/Dialogs.py:350
msgid "Run a partial upgrade, to install as many updates as possible.\n\n"
"    This can be caused by:\n"
"     * A previous upgrade which didn't complete\n"
"     * Problems with some of the installed software\n"
"     * Unofficial software packages not provided by Ubuntu\n"
"     * Normal changes of a pre-release version of Ubuntu"
msgstr ""

#: ../UpdateManager/Dialogs.py:361
msgid "_Partial Upgrade"
msgstr ""

#: ../UpdateManager/Dialogs.py:362
msgid "_Continue"
msgstr ""

#: ../UpdateManager/Dialogs.py:403
msgid "_Try Again"
msgstr ""

#: ../UpdateManager/Dialogs.py:417
msgid "The computer needs to restart to finish installing updates."
msgstr ""

#: ../UpdateManager/Dialogs.py:421
msgid "Restart _Later"
msgstr ""

#: ../UpdateManager/Dialogs.py:423
msgid "_Restart Now"
msgstr ""

#. Basic GTK+ parameters
#: ../UpdateManager/UpdateManager.py:101 ../data/update-manager.desktop.in.h:1
#: ../data/update-manager.appdata.xml.in.h:1
msgid "Software Updater"
msgstr ""

#: ../UpdateManager/UpdateManager.py:433
msgid "Some software couldn’t be checked for updates."
msgstr ""

#: ../UpdateManager/UpdateManager.py:437
msgid "Updated software is available from a previous check."
msgstr ""

#. we assert a clean cache
#: ../UpdateManager/UpdateManager.py:315
msgid "Software index is broken"
msgstr ""

#: ../UpdateManager/UpdateManager.py:317
msgid "It is impossible to install or remove any software. Please use the package manager \"Synaptic\" or run \"sudo apt-get install -f\" in a terminal to fix this issue at first."
msgstr ""

#: ../UpdateManager/UpdateManager.py:324
msgid "Could not initialize the package information"
msgstr ""

#: ../UpdateManager/UpdateManager.py:326
msgid "An unresolvable problem occurred while initializing the package information.\n\n"
"Please report this bug against the 'update-manager' package and include the following error message:\n"
msgstr ""

#: ../UpdateManager/UpdateManager.py:333
msgid "Could not calculate the upgrade"
msgstr ""

#: ../UpdateManager/UpdateManager.py:335
msgid "An unresolvable problem occurred while calculating the upgrade.\n\n"
"Please report this bug against the 'update-manager' package and include the following error message:\n"
msgstr ""

#: ../UpdateManager/UpdatesAvailable.py:257
msgid "Enable Ubuntu Pro..."
msgstr ""

#: ../UpdateManager/UpdatesAvailable.py:260
msgid "Install Now"
msgstr ""

#: ../UpdateManager/UpdatesAvailable.py:298
msgid "Install or remove"
msgstr ""

#: ../UpdateManager/UpdatesAvailable.py:342
msgid "Download"
msgstr ""

#: ../UpdateManager/UpdatesAvailable.py:421
msgid "_Remind Me Later"
msgstr ""

#. upload_archive = version_match.group(2).strip()
#: ../UpdateManager/UpdatesAvailable.py:585
#, python-format
msgid "Version %s: \n"
msgstr ""

#: ../UpdateManager/UpdatesAvailable.py:662
msgid "No network connection detected, you can not download changelog information."
msgstr ""

#: ../UpdateManager/UpdatesAvailable.py:692
msgid "Downloading list of changes..."
msgstr ""

#: ../UpdateManager/UpdatesAvailable.py:733
msgid "_Deselect All"
msgstr ""

#: ../UpdateManager/UpdatesAvailable.py:740
msgid "Select _All"
msgstr ""

#: ../UpdateManager/UpdatesAvailable.py:844
#, python-format
msgid "%s will be downloaded."
msgstr ""

#: ../UpdateManager/UpdatesAvailable.py:860
msgid "The update has already been downloaded."
msgid_plural "The updates have already been downloaded."
msgstr[0] ""
msgstr[1] ""
msgstr[2] ""
msgstr[3] ""

#: ../UpdateManager/UpdatesAvailable.py:869
msgid "You need to enable Ubuntu Pro to install these updates."
msgstr ""

#: ../UpdateManager/UpdatesAvailable.py:873
msgid "There are no updates to install."
msgstr ""

#: ../UpdateManager/UpdatesAvailable.py:883
msgid "Unknown download size."
msgstr ""

#: ../UpdateManager/UpdatesAvailable.py:911
#, python-format
msgid "Updated software has been issued since %s %s was released. Do you want to install it now?"
msgstr ""

#: ../UpdateManager/UpdatesAvailable.py:917
msgid "Updated software is available for this computer. Do you want to install it now?"
msgstr ""

#: ../UpdateManager/UpdatesAvailable.py:922
msgid "The computer also needs to restart to finish installing previous updates."
msgstr ""

#. print("on_button_install_clicked")
#: ../UpdateManager/UpdatesAvailable.py:954
msgid "Not enough free disk space"
msgstr ""

#: ../UpdateManager/UpdatesAvailable.py:956
#, python-format
msgid "The upgrade needs a total of %s free space on disk '%s'. Please free at least an additional %s of disk space on '%s'. %s"
msgstr ""

#: ../UpdateManager/UpdatesAvailable.py:961
msgid "Remove temporary packages of former installations using 'sudo apt clean'."
msgstr ""

#: ../UpdateManager/UpdatesAvailable.py:965
msgid "You can remove old kernels using 'sudo apt autoremove', and you could also set COMPRESS=xz in /etc/initramfs-tools/initramfs.conf to reduce the size of your initramfs."
msgstr ""

#: ../UpdateManager/UpdatesAvailable.py:970
msgid "Empty your trash and remove temporary packages of former installations using 'sudo apt clean'."
msgstr ""

#: ../UpdateManager/UpdatesAvailable.py:973
msgid "Reboot to clean up files in /tmp."
msgstr ""

#: ../UpdateManager/UpdatesAvailable.py:1035
msgid "Connecting..."
msgstr ""

#: ../UpdateManager/UpdatesAvailable.py:1055
msgid "You may not be able to check for updates or download new updates."
msgstr ""

#: ../UpdateManager/UpdatesAvailable.py:1229
msgid "Improved hardware support"
msgstr ""

#: ../UpdateManager/UpdatesAvailable.py:1233
msgid "Security updates"
msgstr ""

#: ../UpdateManager/UpdatesAvailable.py:1236
msgid "Other updates"
msgstr ""

#: ../UpdateManager/UpdatesAvailable.py:1240
msgid "Unused kernel updates to be removed"
msgstr ""

#: ../UpdateManager/UpdatesAvailable.py:1246
msgid "Duplicate packages to be removed"
msgstr ""

#: ../UpdateManager/UpdatesAvailable.py:1252
msgid "Ubuntu Pro security updates"
msgstr ""

#: ../UpdateManager/UpdatesAvailable.py:1259
msgid "Ubuntu Pro security updates (enable in Settings…)"
msgstr ""

#: ../UpdateManager/UnitySupport.py:79
msgid "Install All Available Updates"
msgstr ""

#: ../UpdateManager/Core/MyCache.py:461
msgid "This update does not come from a source that supports changelogs."
msgstr ""

#: ../UpdateManager/Core/MyCache.py:468 ../UpdateManager/Core/MyCache.py:519
msgid "Failed to download the list of changes. \n"
"Please check your Internet connection."
msgstr ""

#: ../UpdateManager/Core/MyCache.py:486
#, python-format
msgid "Changes for %s versions:\n"
"Installed version: %s\n"
"Available version: %s\n\n"
msgstr ""

#: ../UpdateManager/Core/MyCache.py:504
#, python-format
msgid "The changelog does not contain any relevant changes.\n\n"
"Please use http://launchpad.net/ubuntu/+source/%s/%s/+changelog\n"
"until the changes become available or try again later."
msgstr ""

#: ../UpdateManager/Core/MyCache.py:511
#, python-format
msgid "The list of changes is not available yet.\n\n"
"Please use http://launchpad.net/ubuntu/+source/%s/%s/+changelog\n"
"until the changes become available or try again later."
msgstr ""

#. Translators: the %s is a distro name, like 'Ubuntu' and 'base' as in
#. the core components and packages.
#: ../UpdateManager/Core/UpdateList.py:185
#, python-format
msgid "%s base"
msgstr ""

#. TRANSLATORS: download size of small updates, e.g. "250 kB"
#: ../UpdateManager/Core/utils.py:497
#, python-format
msgid "%(size).0f kB"
msgid_plural "%(size).0f kB"
msgstr[0] ""
msgstr[1] ""
msgstr[2] ""
msgstr[3] ""

#. TRANSLATORS: download size of updates, e.g. "2.3 MB"
#: ../UpdateManager/Core/utils.py:502
#, python-format
msgid "%.1f MB"
msgstr ""

#: ../data/gtkbuilder/UpdateManager.ui.h:1
msgid "updates"
msgstr ""

#: ../data/gtkbuilder/UpdateManager.ui.h:2
msgid "Details of updates"
msgstr ""

#: ../data/gtkbuilder/UpdateManager.ui.h:3
msgid "The computer will need to restart."
msgstr ""

#: ../data/gtkbuilder/UpdateManager.ui.h:4
msgid "You are connected via roaming and may be charged for the data consumed by this update."
msgstr ""

#: ../data/gtkbuilder/UpdateManager.ui.h:5
msgid "You may want to wait until you’re not using a mobile broadband connection."
msgstr ""

#: ../data/gtkbuilder/UpdateManager.ui.h:6
msgid "It’s safer to connect the computer to AC power before updating."
msgstr ""

#: ../data/update-manager.desktop.in.h:2
msgid "Software Updates"
msgstr ""

#: ../data/update-manager.desktop.in.h:3
#: ../data/update-manager.appdata.xml.in.h:2
msgid "Show and install available updates"
msgstr ""

#: ../data/update-manager.appdata.xml.in.h:3
msgid "Software Updater checks for updates using apt and let you choose which updates to install."
msgstr ""

#: ../update-manager:76
msgid "Show version and exit"
msgstr ""

#: ../update-manager:79
msgid "Directory that contains the data files"
msgstr ""

#: ../update-manager:82
msgid "Check if a new Ubuntu release is available"
msgstr ""

#: ../update-manager:85
msgid "If using the latest supported release, upgrade to the development release"
msgstr ""

#: ../update-manager:89
msgid "Upgrade using the latest proposed version of the release upgrader"
msgstr ""

#: ../update-manager:96
msgid "Do not focus on map when starting"
msgstr ""

#: ../update-manager:99
msgid "Do not check for updates when starting"
msgstr ""

#: ../update-manager:101
msgid "Show debug messages"
msgstr ""

#. Why do we use %s here instead of $strings or {} format placeholders?
#. It's because we don't want to break existing translations.
#: ../janitor/plugincore/exceptions.py:39
#, python-format
msgid "Unimplemented method: %s"
msgstr ""

#: ../janitor/plugincore/core/file_cruft.py:42
msgid "A file on disk"
msgstr ""

#: ../janitor/plugincore/core/missing_package_cruft.py:37
msgid "Install missing package."
msgstr ""

#. 2012-06-08 BAW: i18n string; don't use {} or PEP 292.
#: ../janitor/plugincore/core/missing_package_cruft.py:47
#, python-format
msgid "Package %s should be installed."
msgstr ""

#: ../janitor/plugincore/core/package_cruft.py:47
msgid ".deb package"
msgstr ""

#: ../janitor/plugincore/plugins/langpack_manual_plugin.py:43
#, python-format
msgid "%s needs to be marked as manually installed."
msgstr ""

#: ../janitor/plugincore/plugins/kdelibs4to5_plugin.py:51
msgid "When upgrading, if kdelibs4-dev is installed, kdelibs5-dev needs to be installed. See bugs.launchpad.net, bug #279621 for details."
msgstr ""

#: ../janitor/plugincore/plugins/dpkg_status_plugin.py:40
#, python-format
msgid "%i obsolete entries in the status file"
msgstr ""

#: ../janitor/plugincore/plugins/dpkg_status_plugin.py:43
msgid "Obsolete entries in dpkg status"
msgstr ""

#. pragma: no cover
#: ../janitor/plugincore/plugins/dpkg_status_plugin.py:46
msgid "Obsolete dpkg status entries"
msgstr ""

#: ../janitor/plugincore/plugins/remove_lilo_plugin.py:40
msgid "Remove lilo since grub is also installed.(See bug #314004 for details.)"
msgstr ""

#~ msgid "Changes"
#~ msgstr "Змены"

#~ msgid "Description"
#~ msgstr "Апісанне"

#~ msgid "Updates"
#~ msgstr "Абнаўленні"

#~ msgid "Technical description"
#~ msgstr "Тэхнічнае апісанне"

#~ msgid "Ubuntu Pro (enable in Settings…)"
#~ msgstr "Ubuntu Pro (уключыць у наладах…)"

