# Belarusian translation for update-manager
# Copyright (c) (c) 2006 Canonical Ltd, and Rosetta Contributors 2006
# This file is distributed under the same license as the update-manager package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2006.
#
# Alyaksandr Koshal <alyaksandr.koshal@gmail.com>, 2021
# Вася Пупкін, 2021
# Black Beard (blackbeardboy), 2021
# p k (pkuhto), 2021
# Heorhi Puhachou <h.puhachou@gmail.com>, 2021
# Aleh Gardzey, 2021.
msgid ""
msgstr ""
"Project-Id-Version: update-manager\n"
"Report-Msgid-Bugs-To: sebastian.heinlein@web.de\n"
"POT-Creation-Date: 2023-02-10 19:12+0000\n"
"PO-Revision-Date: 2023-05-27 12:36+0000\n"
"Last-Translator: Ubuntu Belarusian Translators Team <Unknown>\n"
"Language-Team: Belarusian <be@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && "
"n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);\n"
"X-Launchpad-Export-Date: 2023-07-29 11:20+0000\n"
"X-Generator: Launchpad (build d80dbb5bdc9110f3a64cc968928033472d5e0509)\n"
"Language: be\n"

#. TRANSLATORS: %s is a country
#: ../DistUpgrade/distro.py:206 ../DistUpgrade/distro.py:461
#, python-format
msgid "Server for %s"
msgstr "Сервер для %s"

#. More than one server is used. Since we don't handle this case
#. in the user interface we set "custom servers" to true and
#. append a list of all used servers
#: ../DistUpgrade/distro.py:225 ../DistUpgrade/distro.py:237
#: ../DistUpgrade/distro.py:258
msgid "Main server"
msgstr "Галоўны сервер"

#: ../DistUpgrade/distro.py:267
msgid "Custom servers"
msgstr "Адмысловыя серверы"

#: ../DistUpgrade/DistUpgradeCache.py:182
msgid "Remove package in bad state"
msgid_plural "Remove packages in bad state"
msgstr[0] "Выдаліць пакет, пазначаны як памылковы"
msgstr[1] "Выдаліць пакеты, пазначаныя як памылковыя"
msgstr[2] "Выдаліць пакеты ў кепскім стане"

#: ../DistUpgrade/DistUpgradeCache.py:185
#, python-format
msgid ""
"The package '%s' is in an inconsistent state and needs to be reinstalled, "
"but no archive can be found for it. Do you want to remove this package now "
"to continue?"
msgid_plural ""
"The packages '%s' are in an inconsistent state and need to be reinstalled, "
"but no archives can be found for them. Do you want to remove these packages "
"now to continue?"
msgstr[0] ""
"Пакет “%s“ знаходзіцца ў супярэчлівым стане і мусіць быць пераўсталяваны, "
"але немагчыма адшукаць архіў для яго. Ці жадаеце выдаліць зараз гэты пакет?"
msgstr[1] ""
"Пакеты “%s“ знаходзяцца ў супярэчлівым стане і мусіць быць пераўсталяваны, "
"але немагчыма адшукаць архівы для іх. Ці жадаеце выдаліць зараз гэтыя пакеты?"
msgstr[2] ""
"Пакеты “%s“ знаходзяцца ў супярэчлівым стане і мусіць быць пераўсталяваны, "
"але немагчыма адшукаць архівы для іх. Ці жадаеце выдаліць зараз гэтыя пакеты?"

#. FIXME: not ideal error message, but we just reuse a
#. existing one here to avoid a new string
#: ../DistUpgrade/DistUpgradeCache.py:301
msgid "The server may be overloaded"
msgstr "Магчыма сервер перагружаны"

#: ../DistUpgrade/DistUpgradeCache.py:414
msgid "Broken packages"
msgstr "Пакеты з памылкамі"

#: ../DistUpgrade/DistUpgradeCache.py:415
msgid ""
"Your system contains broken packages that couldn't be fixed with this "
"software. Please fix them first using synaptic or apt-get before proceeding."
msgstr ""
"Сістэма змяшчае пашкоджаныя пакеты, якія не могуць быць выпраўленыя гэтай "
"праграмай.  Калі ласка, спачатку выпраўце іх з дапамогай synaptic ці apt-get "
"перш чым працягваць."

#: ../DistUpgrade/DistUpgradeCache.py:660
#, python-format
msgid "Broken packages after upgrade: %s"
msgstr ""

#. the most likely problem is the 3rd party pkgs so don't address
#. foreignPkgs and devRelease being True
#: ../DistUpgrade/DistUpgradeCache.py:665
msgid ""
"An unresolvable problem occurred while calculating the upgrade.\n"
"\n"
" "
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:668
msgid ""
"This was likely caused by:\n"
" * Unofficial software packages not provided by Ubuntu\n"
"Please use the tool 'ppa-purge' from the ppa-purge \n"
"package to remove software from a Launchpad PPA and \n"
"try the upgrade again.\n"
"\n"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:676
msgid ""
"This was caused by:\n"
" * Upgrading to a pre-release version of Ubuntu\n"
"This is most likely a transient problem, \n"
"please try again later.\n"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:683
msgid "This is most likely a transient problem, please try again later."
msgstr "Магчыма, гэта часовая праблема. Паспрабуйце паўтарыць пазней."

#: ../DistUpgrade/DistUpgradeCache.py:686
msgid ""
"If none of this applies, then please report this bug using the command "
"'ubuntu-bug ubuntu-release-upgrader-core' in a terminal. "
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:688
msgid ""
"If you want to investigate this yourself the log files in '/var/log/dist-"
"upgrade' will contain details about the upgrade. Specifically, look at "
"'main.log' and 'apt.log'."
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:694
msgid "Could not calculate the upgrade"
msgstr "Немагчыма падлічыць абнаўленне"

#: ../DistUpgrade/DistUpgradeCache.py:751
msgid "Error authenticating some packages"
msgstr "Памылка аўтэнтыфікацыі некаторых пакетаў"

#: ../DistUpgrade/DistUpgradeCache.py:752
msgid ""
"It was not possible to authenticate some packages. This may be a transient "
"network problem. You may want to try again later. See below for a list of "
"unauthenticated packages."
msgstr ""
"Немагчыма аўтэнтыфікаваць некаторыя пакеты. Гэта можа быць з-за часовай "
"праблемы з сеткай. Вы можаце паспрабаваць паўтарыць дзеяньне пазней. "
"Глядзіце ніжэй спіс неаўтэнтыфікаваных пакетаў."

#: ../DistUpgrade/DistUpgradeCache.py:773
#, python-format
msgid ""
"The package '%s' is marked for removal but it is in the removal deny list."
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:779
#, python-format
msgid "The essential package '%s' is marked for removal."
msgstr "Важны пакет “%s“ пазначаны для выдалення."

#: ../DistUpgrade/DistUpgradeCache.py:788
#, python-format
msgid "Trying to install deny listed version '%s'"
msgstr ""

#: ../DistUpgrade/DistUpgradeCache.py:910
#, python-format
msgid "Can't install '%s'"
msgstr "Немагчыма ўсталяваць \"%s\""

#: ../DistUpgrade/DistUpgradeCache.py:911
msgid ""
"It was impossible to install a required package. Please report this as a bug "
"using 'ubuntu-bug ubuntu-release-upgrader-core' in a terminal."
msgstr ""
"Не атрымалася ўсталяваць патрэбны пакет. Паведаміце аб гэтай памылцы, "
"выкарыстаўшы каманду \"ubuntu-bug ubuntu-release-upgrader-core\" у тэрмінале."

#: ../DistUpgrade/DistUpgradeCache.py:922
msgid "Can't guess meta-package"
msgstr "Немагчыма вызначыць мета-пакет"

#: ../DistUpgrade/DistUpgradeCache.py:923
#, python-format
msgid ""
"Your system does not contain a %s or %s package and it was not possible to "
"detect which version of Ubuntu you are running.\n"
" Please install one of the packages above first using synaptic or apt-get "
"before proceeding."
msgstr ""
"Ваша сістэма не ўтрымлівае такога %s ці такога %s пакета, было немагчыма "
"вызначыць, у якой версіі Убунту вы карыстаецеся.\n"
"  Калі ласка, усталюйце адзін з пакетаў вышэй дапамогай synaptic ці apt-get, "
"перад тым як працягнуць."

#: ../DistUpgrade/DistUpgradeController.py:112
msgid "Reading cache"
msgstr "Чытанне кэша"

#: ../DistUpgrade/DistUpgradeController.py:218
msgid "Unable to get exclusive lock"
msgstr "Памылка пры праверцы аўтэнтычнасці некаторых пакетаў"

#: ../DistUpgrade/DistUpgradeController.py:219
msgid ""
"This usually means that another package management application (like apt-get "
"or aptitude) already running. Please close that application first."
msgstr ""
"Звычайна, гэта азначае, што выконваецца іншая праграма кіравання пакетамі "
"(напрыклад, apt-get або aptitude). Першапачаткова закрыйце гэту праграму."

#: ../DistUpgrade/DistUpgradeController.py:277
msgid "Upgrading over remote connection not supported"
msgstr "Апгрэйд праз аддаленае падлучэнне не падтрымліваецца"

#: ../DistUpgrade/DistUpgradeController.py:278
msgid ""
"You are running the upgrade over a remote ssh connection with a frontend "
"that does not support this. Please try a text mode upgrade with 'do-release-"
"upgrade'.\n"
"\n"
"The upgrade will abort now. Please try without ssh."
msgstr ""
"Вы спрабуеце выканаць абнаўленьне праз ssh-злучэнне з непадтрымліваемым "
"кліентам. Абнавіцеся ў тэкставым рэжыме праз \"do-release-upgrade\".\n"
"\n"
"Абнаўленне прыпынена. Паспрабуйце без ssh."

#: ../DistUpgrade/DistUpgradeController.py:292
msgid "Continue running under SSH?"
msgstr "Працягваць выкананне праз SSH?"

#: ../DistUpgrade/DistUpgradeController.py:293
#, python-format
msgid ""
"This session appears to be running under ssh. It is not recommended to "
"perform a upgrade over ssh currently because in case of failure it is harder "
"to recover.\n"
"\n"
"If you continue, an additional ssh daemon will be started at port '%s'.\n"
"Do you want to continue?"
msgstr ""
"Гэты сеанс запушчаны праз ssh. Не рэкамендавана выконваць абнаўленьне праз "
"ssh, бо ў выпадку няўдачы аднаўленне будзе вельмі складаным.\n"
"\n"
"Калі Вы працягнеце, дадатковая служба ssh будзе запушчана на порце «%s».\n"
"Жадаеце працягнуць?"

#: ../DistUpgrade/DistUpgradeController.py:307
msgid "Starting additional sshd"
msgstr "Запуск дадатковай sshd"

#: ../DistUpgrade/DistUpgradeController.py:308
#, python-format
msgid ""
"To make recovery in case of failure easier, an additional sshd will be "
"started on port '%s'. If anything goes wrong with the running ssh you can "
"still connect to the additional one.\n"
msgstr ""
"Каб зрабіць аднаўленне ў выпадку памылкі лягчэйшым, на порце '%s' будзе "
"запушчаная дадатковая служба sshd. Калі нешта здарыцца, з дапамогай ssh Вы "
"зможаце далучыцца да дадзенай службы.\n"

#: ../DistUpgrade/DistUpgradeController.py:316
#, python-format
msgid ""
"If you run a firewall, you may need to temporarily open this port. As this "
"is potentially dangerous it's not done automatically. You can open the port "
"with e.g.:\n"
"'%s'"
msgstr ""
"Калі ў вас уключаны брандмаўэр, вам магчыма трэба часова адкрыць гэты порт. "
"Паколькі гэта патэнцыйна небяспечна, порт не адкрыецца аўтаматычна. Вы "
"можаце адкрыць наступны спосабам:\n"
"«%s» порт."

#: ../DistUpgrade/DistUpgradeController.py:394
#: ../DistUpgrade/DistUpgradeController.py:418
msgid "Can not upgrade"
msgstr "Немагчыма абнавіць"

#: ../DistUpgrade/DistUpgradeController.py:395
#, python-format
msgid "An upgrade from '%s' to '%s' is not supported with this tool."
msgstr "Абнаўленне ад '%s' да '%s' не падтрымліваецца дадзенай прыладай."

#: ../DistUpgrade/DistUpgradeController.py:419
msgid ""
"Your python3 install is corrupted. Please fix the '/usr/bin/python3' symlink."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:448
#, python-format
msgid "Can not write to '%s'"
msgstr "Немагчыма запісаць у '%s'"

#: ../DistUpgrade/DistUpgradeController.py:449
#, python-format
msgid ""
"Its not possible to write to the system directory '%s' on your system. The "
"upgrade can not continue.\n"
"Please make sure that the system directory is writable."
msgstr ""
"Няма доступу да сістэмнага каталога '%s'  у вашай сістэме. Абнаўленне не "
"можа працягвацца.\n"
" Калі ласка, пераканайцеся ў наяўнасці доступу да сістэмнага каталога."

#: ../DistUpgrade/DistUpgradeController.py:628
#, python-format
msgid "Not for humans during development stage of release %s"
msgstr "Не для людзей, пакуль знаходзіцца на стадыі распрацоўкі рэлізу %s"

#: ../DistUpgrade/DistUpgradeController.py:729
#, python-format
msgid "disabled on upgrade to %s"
msgstr "заблакавана пры абнаўленні да %s"

#: ../DistUpgrade/DistUpgradeController.py:788
msgid "No valid sources.list entry found"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:789
#, python-format
msgid ""
"While scanning your repository information no entry about %s could be "
"found.\n"
"\n"
"An upgrade might not succeed.\n"
"\n"
"Do you want to continue anyway?"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:799
msgid "No valid mirror found"
msgstr "Не знойдзена ніводнага дзейснага люстэрка"

#: ../DistUpgrade/DistUpgradeController.py:800
#, python-format
msgid ""
"While scanning your repository information no mirror entry for the upgrade "
"was found. This can happen if you run an internal mirror or if the mirror "
"information is out of date.\n"
"\n"
"Do you want to rewrite your 'sources.list' file anyway? If you choose 'Yes' "
"here it will update all '%s' to '%s' entries.\n"
"If you select 'No' the upgrade will cancel."
msgstr ""
"Пры сканаванні сховішча не было знойдзена люстэрка для абнаўлення. Такое "
"магло адбыцца ў выпадку выкарыстання ўнутранага люстэрка ці інфармацыя аб "
"люстэрках састарэла.\n"
"\n"
"Усё роўна хочаце перапісаць файл крыніц \"sources.list '? Калі вы адкажаце "
"\"Так, тады абновяцца усе запісы ад\"% s \"да\"% s \".\n"
"Калі адкажаце \"Не\" абнаўленне будзе спынена."

#. hm, still nothing useful ...
#: ../DistUpgrade/DistUpgradeController.py:820
msgid "Generate default sources?"
msgstr "Згенераваць крыніцы па змаўчанні?"

#: ../DistUpgrade/DistUpgradeController.py:821
#, python-format
msgid ""
"After scanning your 'sources.list' no valid entry for '%s' was found.\n"
"\n"
"Should default entries for '%s' be added? If you select 'No', the upgrade "
"will cancel."
msgstr ""
"Ня знойдзены запіс для '%s' у файле 'sources.list'.\n"
"\n"
"Дадаць стандартны запіс для '%s'? Выбар «Не» азначае адмову ад абнаўлення."

#: ../DistUpgrade/DistUpgradeController.py:856
#: ../DistUpgrade/DistUpgradeController.py:862
msgid "Repository information invalid"
msgstr "Памылковыя звесткі пра рэпазіторый"

#: ../DistUpgrade/DistUpgradeController.py:857
msgid ""
"Upgrading the repository information resulted in a invalid file so a bug "
"reporting process is being started."
msgstr ""
"Абнаўленне звестак рэпазіторыя прывяло да стварэння памылковага файла. "
"Выконваецца запуск сістэмы апавяшчэння пра памылку."

#: ../DistUpgrade/DistUpgradeController.py:863
msgid ""
"Upgrading the repository information resulted in a invalid file. To report a "
"bug install apport and then execute 'apport-bug ubuntu-release-upgrader'."
msgstr ""
"Абнаўленне звестак рэпазіторыя прывяло да стварэння памылковага файла. Каб "
"паведаміць пра памылку ўсталявання, усталюйце apport і выканайце каманду "
"'apport-bug ubuntu-release-upgrader'."

#: ../DistUpgrade/DistUpgradeController.py:872
msgid "Third party sources disabled"
msgstr "Зыходнікі ад трэціх бакоў - адключаныя"

#: ../DistUpgrade/DistUpgradeController.py:873
msgid ""
"Some third party entries in your sources.list were disabled. You can re-"
"enable them after the upgrade with the 'software-properties' tool or your "
"package manager."
msgstr ""
"Некаторыя пабочныя крыніцы ў файле «sources.list» былі адключаныя. Вы "
"зможаце іх зноў уключыць пасля абнаўлення з дапамогай утыліты «Крыніцы "
"ўсталёўкі» альбо вашага мэнэджара пакункаў."

#: ../DistUpgrade/DistUpgradeController.py:915
msgid "Package in inconsistent state"
msgid_plural "Packages in inconsistent state"
msgstr[0] "Пакунак у нестабільным стане"
msgstr[1] "Пакункі ў няўстойлівым стане"
msgstr[2] "Пакункаў у наўстойлівым стане"

#: ../DistUpgrade/DistUpgradeController.py:918
#, python-format
msgid ""
"The package '%s' is in an inconsistent state and needs to be reinstalled, "
"but no archive can be found for it. Please reinstall the package manually or "
"remove it from the system."
msgid_plural ""
"The packages '%s' are in an inconsistent state and need to be reinstalled, "
"but no archive can be found for them. Please reinstall the packages manually "
"or remove them from the system."
msgstr[0] ""
"Пакунак '%s' няўстойлівы і павінен быць пераўсталяваны, аднак, для яго ня "
"знойдзен адпаведны архіў. Калі ласка, пераўсталюйце гэты пакунак уручную "
"альбо выдаліце яго з сістэмы."
msgstr[1] ""
"Пакункі '%s' няўстойлівыя і павінны быць пераўсталяваны, аднак, для іх ня "
"знойдзены адпаведныя архівы. Калі ласка, пераўсталюйце гэтыя пакункі уручную "
"альбо выдаліце іх з сістэмы."
msgstr[2] ""
"Пакункі '%s' няўстойлівыя і павінны быць пераўсталяваны, аднак, для іх ня "
"знойдзены адпаведныя архівы. Калі ласка, пераўсталюйце гэтыя пакункі уручную "
"альбо выдаліце іх з сістэмы."

#: ../DistUpgrade/DistUpgradeController.py:979
msgid "Error during update"
msgstr "Памылка падчас абнаўлення"

#: ../DistUpgrade/DistUpgradeController.py:980
msgid ""
"A problem occurred during the update. This is usually some sort of network "
"problem, please check your network connection and retry."
msgstr ""
"Пры абнаўленні паўстала праблема. Звычайна гэта бывае выклікана праблемамі ў "
"сетцы. Праверце сеткавыя злучэнні і паспрабуйце яшчэ."

#: ../DistUpgrade/DistUpgradeController.py:1023
#: ../DistUpgrade/DistUpgradeController.py:1028
msgid "EFI System Partition (ESP) not usable"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1024
msgid ""
"Your EFI System Partition (ESP) is not mounted at /boot/efi. Please ensure "
"that it is properly configured and try again."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1029
msgid ""
"The EFI System Partition (ESP) mounted at /boot/efi is not writable. Please "
"mount this partition read-write and try again."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1036
msgid "Not enough free disk space"
msgstr "Бракуе дыскавае прасторы"

#. TRANSLATORS: you can change the order of the sentence,
#. make sure to keep all {str_*} string untranslated.
#: ../DistUpgrade/DistUpgradeController.py:1039
#, python-brace-format
msgid ""
"The upgrade has aborted. The upgrade needs a total of {str_total} free space "
"on disk '{str_dir}'. Please free at least an additional {str_needed} of disk "
"space on '{str_dir}'. {str_remedy}"
msgstr ""

#. specific ways to resolve lack of free space
#: ../DistUpgrade/DistUpgradeController.py:1044
msgid ""
"Remove temporary packages of former installations using 'sudo apt clean'."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1046
msgid ""
"You can remove old kernels using 'sudo apt autoremove' and you could also "
"set COMPRESS=xz in /etc/initramfs-tools/initramfs.conf to reduce the size of "
"your initramfs."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1051
msgid ""
"Empty your trash and remove temporary packages of former installations using "
"'sudo apt-get clean'."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1054
msgid "Reboot to clean up files in /tmp."
msgstr ""

#. calc the dist-upgrade and see if the removals are ok/expected
#. do the dist-upgrade
#: ../DistUpgrade/DistUpgradeController.py:1093
#: ../DistUpgrade/DistUpgradeController.py:1938
#: ../DistUpgrade/DistUpgradeController.py:1990
msgid "Calculating the changes"
msgstr "Падлічыць змены"

#. ask the user
#: ../DistUpgrade/DistUpgradeController.py:1137
msgid "Do you want to start the upgrade?"
msgstr "Ці жадаеце пачаць абнаўленне?"

#: ../DistUpgrade/DistUpgradeController.py:1156
#, python-format
msgid ""
"Livepatch security updates are not available for Ubuntu %s. If you upgrade, "
"Livepatch will turn off."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1228
msgid "Upgrade canceled"
msgstr "Абнаўленне скасавана"

#: ../DistUpgrade/DistUpgradeController.py:1229
msgid ""
"The upgrade will cancel now and the original system state will be restored. "
"You can resume the upgrade at a later time."
msgstr ""
"Гэта абнаўленне будзе зараз скасавана і адбудзецца аднаўленне зыходнага "
"стану сістэмы. Вы можаце працягнуць гэта абнаўленне пазней."

#: ../DistUpgrade/DistUpgradeController.py:1235
#: ../DistUpgrade/DistUpgradeController.py:1380
msgid "Could not download the upgrades"
msgstr "Не атрымалася загрузіць абнаўленні"

#: ../DistUpgrade/DistUpgradeController.py:1236
msgid ""
"The upgrade has aborted. Please check your Internet connection or "
"installation media and try again. All files downloaded so far have been kept."
msgstr ""
"Абнаўленне было перапынена. Калі ласка, праверце ваша злучэнне з інтэрнэтам "
"або крыніцу ўсталёўкі і паспрабуйце зноў. Усе загружаныя файлы былі "
"захаваныя."

#. FIXME: strings are not good, but we are in string freeze
#. currently
#: ../DistUpgrade/DistUpgradeController.py:1329
#: ../DistUpgrade/DistUpgradeController.py:1368
#: ../DistUpgrade/DistUpgradeController.py:1485
msgid "Error during commit"
msgstr "Памылка пры фіксаванні"

#. generate a new cache
#: ../DistUpgrade/DistUpgradeController.py:1331
#: ../DistUpgrade/DistUpgradeController.py:1370
#: ../DistUpgrade/DistUpgradeController.py:1530
msgid "Restoring original system state"
msgstr "Аднаўленне першапачатковага стану сістэмы"

#: ../DistUpgrade/DistUpgradeController.py:1332
#: ../DistUpgrade/DistUpgradeController.py:1347
#: ../DistUpgrade/DistUpgradeController.py:1371
msgid "Could not install the upgrades"
msgstr "Немагчыма ўсталяваць абнаўленні"

#. invoke the frontend now and show a error message
#: ../DistUpgrade/DistUpgradeController.py:1337
msgid ""
"The upgrade has aborted. Your system could be in an unusable state. A "
"recovery will run now (dpkg --configure -a)."
msgstr ""
"Абнаўленне было скасавана. Ваша сістэма можа апынуцца ў стане непрыдатным "
"для нармальнага выкарыстання. Зараз будзе запушчаны працэс аднаўлення (dpkg -"
"-configure -a)."

#: ../DistUpgrade/DistUpgradeController.py:1342
#, python-format
msgid ""
"\n"
"\n"
"Please report this bug in a browser at "
"http://bugs.launchpad.net/ubuntu/+source/ubuntu-release-upgrader/+filebug "
"and attach the files in /var/log/dist-upgrade/ to the bug report.\n"
"%s"
msgstr ""
"\n"
"\n"
"Паведаміце аб гэтай памылцы на старонцы па адрасе "
"http://bugs.launchpad.net/ubuntu/+source/ubuntu-release-upgrader/+filebug, "
"уклаўшы файлы з /var/log/dist-upgrade/ да справаздачы пра памылку..\n"
"%s"

#: ../DistUpgrade/DistUpgradeController.py:1381
msgid ""
"The upgrade has aborted. Please check your Internet connection or "
"installation media and try again. "
msgstr ""
"Абнаўленне спыненае. Калі ласка праверце злучэнне з Інтэрнэтам, альбо іншую "
"крыніцу ўсталёўкі і паспрабуйце зноў. "

#: ../DistUpgrade/DistUpgradeController.py:1409
msgid "Searching for obsolete software"
msgstr "Пошук састарэлых праграм"

#: ../DistUpgrade/DistUpgradeController.py:1473
msgid "Remove obsolete packages?"
msgstr "Выдаліць састарэлыя пакеты?"

#: ../DistUpgrade/DistUpgradeController.py:1474
#: ../data/gtkbuilder/DistUpgrade.ui.h:8
msgid "_Keep"
msgstr "За_хаваць"

#: ../DistUpgrade/DistUpgradeController.py:1474
msgid "_Remove"
msgstr "_Выдаліць"

#: ../DistUpgrade/DistUpgradeController.py:1486
msgid ""
"A problem occurred during the clean-up. Please see the below message for "
"more information. "
msgstr "Падчас ачысткі паўстала праблема. Падрабязнасці выкладзены ніжэй. "

#. FIXME: instead of error out, fetch and install it
#. here
#: ../DistUpgrade/DistUpgradeController.py:1568
msgid "Required depends is not installed"
msgstr "Неабходныя залежнасці не ўсталяваныя"

#: ../DistUpgrade/DistUpgradeController.py:1569
#, python-format
msgid "The required dependency '%s' is not installed. "
msgstr "Неабходныя залежнасці \"%s\" не ўсталяваныя. "

#. coherence check (check for ubuntu-desktop, brokenCache etc)
#. then open the cache (again)
#: ../DistUpgrade/DistUpgradeController.py:1802
#: ../DistUpgrade/DistUpgradeController.py:1886
msgid "Checking package manager"
msgstr "Праверка менеджара пакетаў"

#: ../DistUpgrade/DistUpgradeController.py:1808
#: ../DistUpgrade/DistUpgradeController.py:1814
msgid "Preparing the upgrade failed"
msgstr "Збой падрыхтоўкі да абнаўлення"

#: ../DistUpgrade/DistUpgradeController.py:1809
msgid ""
"Preparing the system for the upgrade failed so a bug reporting process is "
"being started."
msgstr ""
"Падрыхтоўкі сістэмы да абнаўлення не атрымалася, будзе запушчана праграма "
"справаздач аб памылках."

#: ../DistUpgrade/DistUpgradeController.py:1815
msgid ""
"Preparing the system for the upgrade failed. To report a bug install apport "
"and then execute 'apport-bug ubuntu-release-upgrader'."
msgstr ""
"Падрыхтоўка сістэмы да абнаўлення скончылася няўдачай. Каб паведаміць пра "
"памылку, усталюйце apport і выканайце каманду \"apport-bug ubuntu-release-"
"upgrader\"."

#: ../DistUpgrade/DistUpgradeController.py:1832
#: ../DistUpgrade/DistUpgradeController.py:1842
msgid "Getting upgrade prerequisites failed"
msgstr "Падрыхтоўка да абнаўлення завяршылася няўдала"

#: ../DistUpgrade/DistUpgradeController.py:1833
msgid ""
"The system was unable to get the prerequisites for the upgrade. The upgrade "
"will abort now and restore the original system state.\n"
"\n"
"Additionally, a bug reporting process is being started."
msgstr ""
"Сістэма не можа атрымаць папярэднія рэквізіты для выканання поўнага "
"абнаўлення. Зараз будзе спынена поўнае абнаўленне і выканана аднаўленне "
"зыходнага стану сістэмы.\n"
"\n"
"Выконваецца запуск паведамлення пра няспраўнасць."

#: ../DistUpgrade/DistUpgradeController.py:1843
msgid ""
"The system was unable to get the prerequisites for the upgrade. The upgrade "
"will abort now and restore the original system state.\n"
"\n"
"To report a bug install apport and then execute 'apport-bug ubuntu-release-"
"upgrader'."
msgstr ""
"Сістэма не змагла атрымаць неабходныя ўмовы для абнаўлення. Абнаўленне будзе "
"зараз перапынена і адновіцца зыходны стан сістэмы.\n"
"Каб паведаміць пра памылку ўсталяваць apport, а затым выканайце 'apport-bug "
"ubuntu-release-upgrader'."

#: ../DistUpgrade/DistUpgradeController.py:1877
msgid "Updating repository information"
msgstr "Абнаўленне інфармацыі аб сховішчы"

#: ../DistUpgrade/DistUpgradeController.py:1915
msgid "Invalid package information"
msgstr "Памылковыя звесткі пра пакет"

#: ../DistUpgrade/DistUpgradeController.py:1916
#, python-format
msgid ""
"After updating your package information, the essential package '%s' could "
"not be located. This may be because you have no official mirrors listed in "
"your software sources, or because of excessive load on the mirror you are "
"using. See /etc/apt/sources.list for the current list of configured software "
"sources.\n"
"In the case of an overloaded mirror, you may want to try the upgrade again "
"later."
msgstr ""
"Пасля абнаўлення інфармацыі аб пакеце не ўдалося знайсці важны пакет '%s'. "
"Прычынай гэтага можа быць адсутнасць афіцыйных люстэркаў у вашым спісе "
"крыніц праграмнага забеспячэння або таму, што люстэрка, якое вы "
"выкарыстоўваеце, перагружана. Гл. бягучы спіс наладжаных крыніц праграмнага "
"забеспячэння ў /etc/apt/sources.list.\n"
"Калі люстэрка перагружана, можна зноў паспрабаваць абнавіцца пазней."

#: ../DistUpgrade/DistUpgradeController.py:1945
#: ../DistUpgrade/DistUpgradeController.py:2056
msgid "Fetching"
msgstr "Атрыманне"

#: ../DistUpgrade/DistUpgradeController.py:1952
#: ../DistUpgrade/DistUpgradeController.py:1975
#: ../DistUpgrade/DistUpgradeController.py:2005
#: ../DistUpgrade/DistUpgradeController.py:2060
msgid "Upgrading"
msgstr "Абнаўленне"

#: ../DistUpgrade/DistUpgradeController.py:1954
msgid "Upgrade infeasible"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1955
msgid ""
"The upgrade could not be completed, there were errors during the upgrade "
"process."
msgstr ""

#. don't abort here, because it would restore the sources.list
#: ../DistUpgrade/DistUpgradeController.py:1978
#: ../DistUpgrade/DistUpgradeController.py:1994
msgid "Upgrade incomplete"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:1979
#: ../DistUpgrade/DistUpgradeController.py:1995
msgid ""
"The upgrade has partially completed but there were errors during the upgrade "
"process."
msgstr ""

#. don't abort here, because it would restore the sources.list
#: ../DistUpgrade/DistUpgradeController.py:2010
#: ../DistUpgrade/DistUpgradeController.py:2062
#: ../DistUpgrade/DistUpgradeController.py:2068
#: ../DistUpgrade/DistUpgradeController.py:2079
msgid "Upgrade complete"
msgstr "Абнаўленне скончана"

#: ../DistUpgrade/DistUpgradeController.py:2011
#: ../DistUpgrade/DistUpgradeController.py:2063
#: ../DistUpgrade/DistUpgradeController.py:2069
msgid ""
"The upgrade has completed but there were errors during the upgrade process."
msgstr ""
"Абнаўленне скончана, аднак падчас працэсу абнаўлення здарыліся памылкі."

#: ../DistUpgrade/DistUpgradeController.py:2026
msgid "System upgrade is complete."
msgstr "Абнаўленне сістэмы завершана"

#: ../DistUpgrade/DistUpgradeController.py:2080
msgid "The partial upgrade was completed."
msgstr "Частковае абнаўленне завершана."

#: ../DistUpgrade/DistUpgradeController.py:2101
msgid "Lock screen disabled"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:2102
msgid ""
"Your lock screen has been disabled and will remain disabled during the "
"upgrade."
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:2110
msgid "Unable to disable lock screen"
msgstr ""

#: ../DistUpgrade/DistUpgradeController.py:2111
msgid ""
"It is highly recommended that the lock screen be disabled during the upgrade "
"to prevent later issues. Please ensure your screen lock is disabled before "
"continuing."
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcher.py:107
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:170
msgid "Could not find the release notes"
msgstr "Не атрымалася знайсці заўвагі да выпуску"

#: ../DistUpgrade/DistUpgradeFetcher.py:108
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:171
msgid "The server may be overloaded. "
msgstr "Магчыма, сервер перагружаны. "

#: ../DistUpgrade/DistUpgradeFetcher.py:120
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:175
msgid "Could not download the release notes"
msgstr "Не атрымалася загрузіць заўвагі да выпуску"

#: ../DistUpgrade/DistUpgradeFetcher.py:121
#: ../DistUpgrade/DistUpgradeFetcherCore.py:77
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:176
msgid "Please check your internet connection."
msgstr "Калі ласка, праверце вашае злучэнне з інтэрнэтам."

#: ../DistUpgrade/DistUpgradeFetcherCore.py:72
msgid "Could not find the release announcement"
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:73
msgid "The server may be overloaded."
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:76
msgid "Could not download the release announcement"
msgstr ""

#: ../DistUpgrade/DistUpgradeFetcherCore.py:82
#: ../DistUpgrade/DistUpgradeViewText.py:215
#: ../DistUpgrade/DistUpgradeViewText.py:253
#: ../DistUpgrade/DistUpgradeViewText.py:261
msgid "Continue [yN] "
msgstr "Працягнуць [тН] "

#. TRANSLATORS: the "y" is "yes"
#. TRANSLATORS: first letter of a positive (yes) answer
#: ../DistUpgrade/DistUpgradeFetcherCore.py:84
#: ../DistUpgrade/DistUpgradeViewText.py:219
#: ../DistUpgrade/DistUpgradeViewText.py:264
msgid "y"
msgstr "y"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:101
#, python-format
msgid "authenticate '%(file)s' against '%(signature)s' "
msgstr "аўтэнтыфікаваць '%(file)s' замест '%(signature)s' "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:127
#, python-format
msgid "extracting '%s'"
msgstr "выманне '%s'"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:148
#: ../DistUpgrade/DistUpgradeFetcherCore.py:149
msgid "Could not run the upgrade tool"
msgstr "Не атрымалася запусціць сродак абнаўлення"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:150
msgid ""
"This is most likely a bug in the upgrade tool. Please report it as a bug "
"using the command 'ubuntu-bug ubuntu-release-upgrader-core'."
msgstr ""
"Найбольш верагоднай прычынай можа быць памылка ў інструменце абнаўлення. "
"Паведаміце аб гэтай памылцы з дапамогай каманды \"ubuntu-bug ubuntu-release-"
"upgrader-core\"."

#: ../DistUpgrade/DistUpgradeFetcherCore.py:227
msgid "Upgrade tool signature"
msgstr "Подпіс прылады абнаўлення"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:234
msgid "Upgrade tool"
msgstr "Прылада абнаўлення"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:268
msgid "Failed to fetch"
msgstr "Не магу атрымаць"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:269
msgid "Fetching the upgrade failed. There may be a network problem. "
msgstr "Не магу атрымаць абнаўленне. Магчыма, паўстала праблема з сецівам. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:273
msgid "Authentication failed"
msgstr "Няўдалая ідэнтыфікацыя"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:274
msgid ""
"Authenticating the upgrade failed. There may be a problem with the network "
"or with the server. "
msgstr ""
"Праверка ідэнтыфікацыі абнаўлення не атрымалася. Магчыма, паўстала праблема "
"з сецівам або на серверы. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:279
msgid "Failed to extract"
msgstr "Не магу выняць"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:280
msgid ""
"Extracting the upgrade failed. There may be a problem with the network or "
"with the server. "
msgstr ""
"Не атрымалася выняць абнаўленне. Магчыма, паўстала праблема з сецівам або на "
"серверы. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:285
msgid "Verification failed"
msgstr "Праверка не атрымалася"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:286
msgid ""
"Verifying the upgrade failed.  There may be a problem with the network or "
"with the server. "
msgstr ""
"Праверка абнаўлення завяршылася няўдала. Магчыма, паўстала праблема з "
"сецівам або на серверы. "

#: ../DistUpgrade/DistUpgradeFetcherCore.py:300
#: ../DistUpgrade/DistUpgradeFetcherCore.py:306
msgid "Can not run the upgrade"
msgstr "Не атрымалася запусціць працэс абнаўлення"

#: ../DistUpgrade/DistUpgradeFetcherCore.py:301
msgid ""
"This usually is caused by a system where /tmp is mounted noexec. Please "
"remount without noexec and run the upgrade again."
msgstr ""
"Звычайна паўстае ў сістэме, дзе / tmp змантаваны пад noexec. Калі ласка, "
"перамантуйце без noexec і запусціце абнаўленне зноў."

#: ../DistUpgrade/DistUpgradeFetcherCore.py:307
#, python-format
msgid "The error message is '%s'."
msgstr "Паведамленне аб памылцы «%s»."

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:151
msgid "&Upgrade"
msgstr "&Абнавіць"

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:154
msgid "&Cancel"
msgstr "&Скасаваць"

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:156
#: ../data/gtkbuilder/ReleaseNotes.ui.h:1
msgid "Release Notes"
msgstr "Нататкі да выпуску"

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:191
msgid "Upgrade"
msgstr "Абнаўленне"

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:207
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:222
msgid "Downloading additional package files..."
msgstr "Загрузка дадатковых файлаў пакетаў ..."

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:224
#, python-format
msgid "File %s of %s at %sB/s"
msgstr "Файл %s з %s на хуткасці %sБ/с"

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:228
#, python-format
msgid "File %s of %s"
msgstr "Файл %s з %s"

#. print("mediaChange %s %s" % (medium, drive))
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:235
#: ../DistUpgrade/DistUpgradeViewGtk3.py:127
#: ../DistUpgrade/DistUpgradeViewKDE.py:302
#, python-format
msgid "Please insert '%s' into the drive '%s'"
msgstr "Калі ласка, устаўце \"%s\" у прыладу \"%s\""

#: ../DistUpgrade/DistUpgradeFetcherKDE.py:237
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:242
#: ../DistUpgrade/DistUpgradeFetcherKDE.py:243
#: ../DistUpgrade/DistUpgradeViewKDE.py:303
msgid "Media Change"
msgstr "Змена носьбіта"

#: ../DistUpgrade/DistUpgradeQuirks.py:237
msgid "Your graphics hardware may not be fully supported in Ubuntu 14.04."
msgstr ""
"Ваша графічнае абсталяванне не можа быць цалкам падтрыманым ў Ubuntu 14.04."

#: ../DistUpgrade/DistUpgradeQuirks.py:239
msgid ""
"Running the 'unity' desktop environment is not fully supported by your "
"graphics hardware. You will maybe end up in a very slow environment after "
"the upgrade. Our advice is to keep the LTS version for now. For more "
"information see "
"https://wiki.ubuntu.com/X/Bugs/UpdateManagerWarningForUnity3D Do you still "
"want to continue with the upgrade?"
msgstr ""
"Асяроддзе працоўнага стала \"unity\" падтрымліваецца вашым графічным "
"апаратным забеспячэннем не цалкам. Магчыма, пасля абнаўлення хуткадзейнасць "
"асяроддзя будзе запаволеная. Раім на разе пакінуць версію LTS. Дадатковыя "
"звесткі гл. https://wiki.ubuntu.com/X/Bugs/UpdateManagerWarningForUnity3D Вы "
"ўсё яшчэ хочаце працягнуць абнаўленне?"

#: ../DistUpgrade/DistUpgradeQuirks.py:263
msgid ""
"Your graphics hardware may not be fully supported in Ubuntu 12.04 LTS."
msgstr ""
"Вашае графічнае абсталяванне, магчыма, не будзе падтрымлівацца цалкам у "
"Ubuntu 12.04 LTS"

#: ../DistUpgrade/DistUpgradeQuirks.py:265
msgid ""
"The support in Ubuntu 12.04 LTS for your Intel graphics hardware is limited "
"and you may encounter problems after the upgrade. For more information see "
"https://wiki.ubuntu.com/X/Bugs/UpdateManagerWarningForI8xx Do you want to "
"continue with the upgrade?"
msgstr ""
"Падтрымка вашай відэакарты ў Ubuntu 12.04 LTS будзе абмежаванай і вы можаце "
"сутыкнуцца з праблемамі пасля абнаўлення. Прачытайце падрабязнасці тут "
"https://wiki.ubuntu.com/X/Bugs/UpdateManagerWarningForI8xx \r\n"
"Вы сапраўды хочаце працягнуць абнаўленне?"

#: ../DistUpgrade/DistUpgradeQuirks.py:285
msgid ""
"Upgrading may reduce desktop effects, and performance in games and other "
"graphically intensive programs."
msgstr ""
"Абнаўленне можа выклікаць зніжэнне якасці эфектаў працоўнага стала і "
"прадукцыйнасці ў гульнях і праграмах, што актыўна выкарыстоўваюць графіку."

#: ../DistUpgrade/DistUpgradeQuirks.py:289
msgid ""
"This computer is currently using the AMD 'fglrx' graphics driver. No version "
"of this driver is available that works with your hardware in Ubuntu 10.04 "
"LTS.\n"
"\n"
"Do you want to continue?"
msgstr ""
"На гэтым кампутары выкарыстоўваюцца драйвера AMD 'fglrx'. Няма даступных "
"версій гэтых драйвераў, якія працавалі бы з Вашым абсталяваннем ва 10.04 "
"LTS\n"
"\n"
"Працягнуць?"

#: ../DistUpgrade/DistUpgradeQuirks.py:328
#: ../DistUpgrade/DistUpgradeQuirks.py:397
msgid "Sorry, no more upgrades for this system"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:329
#, python-format
msgid ""
"There will not be any further Ubuntu releases for this system's 'i386' "
"architecture.\n"
"\n"
"Updates for Ubuntu %s will continue until %s."
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:344
msgid "No ARMv6 CPU"
msgstr "Няма працэсара ARMv6"

#: ../DistUpgrade/DistUpgradeQuirks.py:345
msgid ""
"Your system uses an ARM CPU that is older than the ARMv6 architecture. All "
"packages in karmic were built with optimizations requiring ARMv6 as the "
"minimal architecture. It is not possible to upgrade your system to a new "
"Ubuntu release with this hardware."
msgstr ""
"Ваша сістэма выкарыстоўвае працэсар архітэктуры ARM, старэйшы за архітэктуру "
"ARMv6. Усе пакункі ў karmic былі пабудаваны з аптымізацыяй пад архітэктуру "
"ARMv6 і вышэй. Вашу сістэму немагчыма абнавіць да новага рэлізу Ubuntu з "
"бягучым апаратным забеспячэннем."

#: ../DistUpgrade/DistUpgradeQuirks.py:365
msgid ""
"Sorry, this storage driver is not supported in kernels for newer releases"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:367
#, python-format
msgid ""
"There will not be any further Ubuntu releases that provide kernel support "
"for the aufs storage driver.\n"
"\n"
"Please ensure that none of your containers are using the aufs storage "
"driver, remove the directory %s and try again."
msgstr ""

#. from libpam-modules.templates
#: ../DistUpgrade/DistUpgradeQuirks.py:399
msgid "You are using pam_tally or pam_tally2 in your configuration."
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:401
msgid ""
"The pam_tally and pam_tally2 modules have been removed from PAM. You are "
"using one of these modules in your PAM configuration in /etc/pam.d. You must "
"remove the uses of these modules before PAM can be upgraded; including these "
"modules in your PAM configuration after the upgrade will stop users from "
"being able to log into the system."
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:409
msgid "Consider the pam_faillock module as a replacement for pam_tally."
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:398
#, python-format
msgid ""
"There will not be any further Ubuntu releases for this system's POWER8 "
"processor.\n"
"\n"
"Updates for Ubuntu %s will continue until %s."
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:416
msgid "No init available"
msgstr "Служба init недаступна"

#: ../DistUpgrade/DistUpgradeQuirks.py:417
msgid ""
"Your system appears to be a virtualised environment without an init daemon, "
"e.g. Linux-VServer. Ubuntu 10.04 LTS cannot function within this type of "
"environment, requiring an update to your virtual machine configuration "
"first.\n"
"\n"
"Are you sure you want to continue?"
msgstr ""
"Падобна на тое, што Ваша сістэма з'яўляецца віртуалізаваным асяроддзем без "
"службы init, напрыклад Linux-VServer.\n"
"\n"
"Вы ўпэўнены, што хочаце працягнуць?"

#: ../DistUpgrade/DistUpgradeQuirks.py:458
msgid "The Robot Operating System (ROS) is installed"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:459
msgid ""
"It appears that ROS is currently installed. Each ROS release is very strict "
"about the versions of Ubuntu it supports, and Ubuntu upgrades can fail if "
"that guidance isn't followed. Before continuing, please either uninstall "
"ROS, or ensure the ROS release you have installed supports the version of "
"Ubuntu to which you're upgrading.\n"
"\n"
"For ROS 1 releases, refer to REP 3:\n"
"https://www.ros.org/reps/rep-0003.html\n"
"\n"
"For ROS 2 releases, refer to REP 2000:\n"
"https://www.ros.org/reps/rep-2000.html\n"
"\n"
"Are you sure you want to continue?"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:652
msgid "Connection to the Snap Store failed"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:653
msgid ""
"You have the package lxd installed but your system is unable to reach the "
"Snap Store. lxd is now provided via a snap and the release upgrade will fail "
"if snapd is not functional. Please make sure you're connected to the "
"Internet and update any firewall or proxy settings as needed so that you can "
"reach api.snapcraft.io. If you are an enterprise with a firewall setup you "
"may want to configure a Snap Store proxy."
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:668
msgid "Connection to Snap Store failed"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:669
msgid ""
"Your system does not have a connection to the Snap Store. For the best "
"upgrade experience make sure that your system can connect to "
"api.snapcraft.io.\n"
"Do you still want to continue with the upgrade?"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:678
msgid "Outdated snapd package"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:679
msgid ""
"Your system does not have the latest version of snapd. Please update the "
"version of snapd on your system to improve the upgrade experience.\n"
"Do you still want to continue with the upgrade?"
msgstr ""

#. now perform direct API calls to the store, requesting size
#. information for each of the snaps needing installation
#: ../DistUpgrade/DistUpgradeQuirks.py:704
msgid "Calculating snap size requirements"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:735
msgid "Processing snap replacements"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:741
#, python-format
msgid "refreshing snap %s"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:745
#, python-format
msgid "removing snap %s"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:748
#, python-format
msgid "installing snap %s"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:777
msgid "PAE not enabled"
msgstr "PAE не ўключана"

#: ../DistUpgrade/DistUpgradeQuirks.py:778
msgid ""
"Your system uses a CPU that does not have PAE enabled. Ubuntu only supports "
"non-PAE systems up to Ubuntu 12.04. To upgrade to a later version of Ubuntu, "
"you must enable PAE (if this is possible) see:\n"
"http://help.ubuntu.com/community/EnablingPAE"
msgstr ""
"У вашай сістэме выкарыстоўваецца працэсар, у якім не ўключаныя Інструкцыі "
"PAE. Карыстацца Ubuntu ў сістэмах без PAE можна толькі ў версіі Ubuntu "
"12.10. Абнаўленне да новай версіі Ubuntu запатрабуе ўключэння PAE (калі гэта "
"магчыма). Гл.: Http://help.ubuntu.com/community/EnablingPAE"

#: ../DistUpgrade/DistUpgradeQuirks.py:1074
msgid "universe component not enabled"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:1075
#, python-format
msgid ""
"You have the package %s installed which is a python2 package. python2 has "
"been deprecated in Ubuntu 20.04 LTS and is now available from the universe "
"component of the Ubuntu archive. To ensure any existing third party code you "
"have installed continues to work the release upgrade process would install "
"%s for you. However, the universe component of the archive is not enabled on "
"this system. For the upgrade process to proceed you should either enable the "
"universe component in /etc/apt/sources.list or remove %s"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:1187
msgid "Checking for installed snaps"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:1526
msgid "NVIDIA driver metapackage unavailable"
msgstr ""

#: ../DistUpgrade/DistUpgradeQuirks.py:1527
#, python-format
msgid ""
"Your system has the package libnvidia-gl-%s installed but the corresponding "
"metapackage nvidia-driver-%s is not installed and is not available to be "
"installed. The upgrade process was not able to automatically fix this issue "
"and consequently the upgrade will now exit."
msgstr ""

#: ../DistUpgrade/DistUpgradeMain.py:62
msgid ""
"Use frontend. Currently available: \n"
"DistUpgradeViewText, DistUpgradeViewGtk, DistUpgradeViewKDE"
msgstr ""
"Выкарстоўваць інтэрфэйс. Зараз даступны: \n"
"DistUpgradeViewText, DistUpgradeViewGtk, DistUpgradeViewKDE"

#: ../DistUpgrade/DistUpgradeMain.py:65
msgid "*DEPRECATED* this option will be ignored"
msgstr "Гэты параметр САСТАРЭЎ і не будзе ўлічвацца"

#: ../DistUpgrade/DistUpgradeMain.py:68
msgid "Perform a partial upgrade only (no sources.list rewriting)"
msgstr ""
"Падрыхтаваць толькі частковае абнаўленне (sources.list ня будзе перазапісаны)"

#: ../DistUpgrade/DistUpgradeMain.py:71
msgid "Disable GNU screen support"
msgstr "Адключыць падтрымку экрана GNU"

#: ../DistUpgrade/DistUpgradeMain.py:73
msgid "Set datadir"
msgstr "Наладзіць каталог з дадзенымі"

#: ../DistUpgrade/DistUpgradeMain.py:76
msgid "Upgrade to the development release"
msgstr "Абнавіцца да выпуску, што распрацоўваецца"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:148
#: ../DistUpgrade/DistUpgradeViewKDE.py:316
msgid "Fetching is complete"
msgstr "Загрузка скончана"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:163
#: ../DistUpgrade/DistUpgradeViewKDE.py:332
#, python-format
msgid "Fetching file %li of %li at %sB/s"
msgstr "Загрузка файла %li з %li на хуткасці %sБайт/с"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:165
#: ../DistUpgrade/DistUpgradeViewGtk3.py:327
#: ../DistUpgrade/DistUpgradeViewKDE.py:333
#: ../DistUpgrade/DistUpgradeViewKDE.py:483
#, python-format
msgid "About %s remaining"
msgstr "Засталося прыблізна %s"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:168
#: ../DistUpgrade/DistUpgradeViewKDE.py:335
#, python-format
msgid "Fetching file %li of %li"
msgstr "Загрузка файла %li з %li"

#. FIXME: add support for the timeout
#. of the terminal (to display something useful then)
#. -> longer term, move this code into python-apt
#: ../DistUpgrade/DistUpgradeViewGtk3.py:200
#: ../DistUpgrade/DistUpgradeViewKDE.py:373
msgid "Applying changes"
msgstr "Ужыванне зменаў"

#. we do not report followup errors from earlier failures
#: ../DistUpgrade/DistUpgradeViewGtk3.py:226
#: ../DistUpgrade/DistUpgradeViewKDE.py:386
msgid "dependency problems - leaving unconfigured"
msgstr "праблемы залежнасьцяў — пакідаем неналаджанымі"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:231
#: ../DistUpgrade/DistUpgradeViewKDE.py:388
#, python-format
msgid "Could not install '%s'"
msgstr "Немагчыма ўсталяваць \"%s\""

#: ../DistUpgrade/DistUpgradeViewGtk3.py:232
#: ../DistUpgrade/DistUpgradeViewKDE.py:389
#, python-format
msgid ""
"The upgrade will continue but the '%s' package may not be in a working "
"state. Please consider submitting a bug report about it."
msgstr ""
"Абнаўленне будзе працягнута, але '%s' пакунак(аў) могуць быць у непрацоўным "
"стане. Калі ласка, разглядзіце магчымасць аб паданні справаздачы на конт "
"памылкі."

#. self.expander.set_expanded(True)
#: ../DistUpgrade/DistUpgradeViewGtk3.py:249
#: ../DistUpgrade/DistUpgradeViewKDE.py:411
#, python-format
msgid ""
"Replace the customized configuration file\n"
"'%s'?"
msgstr ""
"Замяніць адмысловы файл наладкі\n"
" \"%s\"?"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:250
#: ../DistUpgrade/DistUpgradeViewKDE.py:412
msgid ""
"You will lose any changes you have made to this configuration file if you "
"choose to replace it with a newer version."
msgstr ""
"Вы страціце ўсе змены, якія зрабілі ў гэтым файле канфігурацыі, калі "
"заменіце яго новай версіяй."

#: ../DistUpgrade/DistUpgradeViewGtk3.py:270
#: ../DistUpgrade/DistUpgradeViewKDE.py:435
msgid "The 'diff' command was not found"
msgstr "Ня знойдзена праграма \"diff\""

#: ../DistUpgrade/DistUpgradeViewGtk3.py:542
#: ../DistUpgrade/DistUpgradeViewText.py:140
msgid "A fatal error occurred"
msgstr "Адбылася крытычная памылка"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:543
msgid ""
"Please report this as a bug (if you haven't already) and include the files "
"/var/log/dist-upgrade/main.log and /var/log/dist-upgrade/apt.log in your "
"report. The upgrade has aborted.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""
"Паведаміце пра гэту памылку (калі вы яшчэ не зрабілі гэта) і далучыце файлы "
"/var/log/dist-upgrade/main.log і /var/log/dist-upgrade/apt.log у вашу "
"справаздачу. Абнаўленне было перарвана.\n"
"Ваш арыгінальны файл sources.list быў захаваны ў "
"/etc/apt/sources.list.distUpgrade."

#: ../DistUpgrade/DistUpgradeViewGtk3.py:573
msgid "Ctrl-c pressed"
msgstr "націснута Ctrl-c"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:574
msgid ""
"This will abort the operation and may leave the system in a broken state. "
"Are you sure you want to do that?"
msgstr ""
"Гэта скасуе працэс і сістэма можа стаць непрацаздольнай. \r\n"
"Вы сапраўды хочаце зрабіць гэта ?"

#. append warning
#: ../DistUpgrade/DistUpgradeViewGtk3.py:713
msgid "To prevent data loss close all open applications and documents."
msgstr ""
"Каб пазбегнуць страты дадзеных, зачыніце ўсе адчыненыя праграмы і дакументы."

#: ../DistUpgrade/DistUpgradeViewGtk3.py:727
#, python-format
msgid "No longer supported by Canonical (%s)"
msgstr "Больш не падтрымліваецца Canonical (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:728
#, python-format
msgid "<b>Downgrade (%s)</b>"
msgstr "<b>Усталяванне старой версіі (%s)</b>"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:729
#, python-format
msgid "Remove (%s)"
msgstr "Выдаліць (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:730
#, python-format
msgid "No longer needed (%s)"
msgstr "Больш не патрэбны (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:731
#, python-format
msgid "Install (%s)"
msgstr "Усталяваць (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:732
#, python-format
msgid "Upgrade (%s)"
msgstr "Абнавіць (%s)"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:780
msgid "Cancel"
msgstr "Скасаваць"

#: ../DistUpgrade/DistUpgradeViewGtk3.py:781
#: ../DistUpgrade/DistUpgradeViewKDE.py:914
msgid "Continue"
msgstr ""

#: ../DistUpgrade/DistUpgradeViewKDE.py:447
msgid "Show Difference >>>"
msgstr "Паказаць адрозненні >>>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:450
msgid "<<< Hide Difference"
msgstr "<<< Схаваць адрозненні"

#: ../DistUpgrade/DistUpgradeViewKDE.py:676
msgid "Error"
msgstr "Памылка"

#: ../DistUpgrade/DistUpgradeViewKDE.py:728
msgid "Show Terminal >>>"
msgstr "Паказаць тэрмінал >>>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:731
msgid "<<< Hide Terminal"
msgstr "<<< Схаваць тэрмінал"

#: ../DistUpgrade/DistUpgradeViewKDE.py:804
msgid "Information"
msgstr "Інфармацыя"

#: ../DistUpgrade/DistUpgradeViewKDE.py:852
msgid "&Start Upgrade"
msgstr "&Пачаць абнаўленне"

#: ../DistUpgrade/DistUpgradeViewKDE.py:854
#: ../DistUpgrade/DistUpgradeViewKDE.py:898
#: ../DistUpgrade/DistUpgradeViewKDE.py:901
#: ../data/gtkbuilder/DistUpgrade.ui.h:7
msgid "Details"
msgstr "Дэталі"

#: ../DistUpgrade/DistUpgradeViewKDE.py:876
#, python-format
msgid "No longer supported %s"
msgstr "Больш не падтрымліваецца (%s)"

#: ../DistUpgrade/DistUpgradeViewKDE.py:878
#, python-format
msgid "Remove %s"
msgstr "Выдаліць %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:880
#: ../DistUpgrade/DistUpgradeViewText.py:239
#, python-format
msgid "Remove (was auto installed) %s"
msgstr "Выдаліць %s (было ўсталявана аўтаматычна)"

#: ../DistUpgrade/DistUpgradeViewKDE.py:882
#, python-format
msgid "Install %s"
msgstr "Усталёўка %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:884
#, python-format
msgid "Upgrade %s"
msgstr "Абнаўленне %s"

#: ../DistUpgrade/DistUpgradeViewKDE.py:931
#: ../DistUpgrade/DistUpgradeViewText.py:292
msgid "Restart required"
msgstr "Патрабуецца перазагрузка"

#: ../DistUpgrade/DistUpgradeViewKDE.py:931
msgid "<b><big>Restart the system to complete the upgrade</big></b>"
msgstr "<b><big>Перагрузіце сістэму для завяршэння абнаўлення</big></b>"

#: ../DistUpgrade/DistUpgradeViewKDE.py:934
#: ../data/gtkbuilder/DistUpgrade.ui.h:14
msgid "_Restart Now"
msgstr "Пера_запусціць"

#: ../DistUpgrade/DistUpgradeViewKDE.py:935
msgid "&Close"
msgstr "&Зачыніць"

#. FIXME make this user friendly
#: ../DistUpgrade/DistUpgradeViewKDE.py:952
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly advised to resume the upgrade."
msgstr ""
"<b><big>Перарваць абнаўленне?</big></b>\n"
"Калі вы перапыніце абнаўленне, сістэма можа працаваць нестабільна. "
"Настойліва рэкамендуем працягваць абнаўленне."

#: ../DistUpgrade/DistUpgradeViewKDE.py:956
msgid "Cancel Upgrade?"
msgstr "Скасаваць абнаўленне?"

#: ../DistUpgrade/DistUpgradeView.py:82
#, python-format
msgid "%li day"
msgid_plural "%li days"
msgstr[0] "%li дзень"
msgstr[1] "%li дні"
msgstr[2] "%li дзён"

#: ../DistUpgrade/DistUpgradeView.py:84
#, python-format
msgid "%li hour"
msgid_plural "%li hours"
msgstr[0] "%li гадзіна"
msgstr[1] "%li гадзіны"
msgstr[2] "%li гадзін"

#: ../DistUpgrade/DistUpgradeView.py:86
#, python-format
msgid "%li minute"
msgid_plural "%li minutes"
msgstr[0] "%li хвіліна"
msgstr[1] "%li хвіліны"
msgstr[2] "%li хвілін"

#: ../DistUpgrade/DistUpgradeView.py:87
#, python-format
msgid "%li second"
msgid_plural "%li seconds"
msgstr[0] "%li сэкунда"
msgstr[1] "%li сэкунды"
msgstr[2] "%li сэкундаў"

#. TRANSLATORS: you can alter the ordering of the remaining time
#. information here if you shuffle %(str_days)s %(str_hours)s %(str_minutes)s
#. around. Make sure to keep all '$(str_*)s' in the translated string
#. and do NOT change anything appart from the ordering.
#. 
#. %(str_hours)s will be either "1 hour" or "2 hours" depending on the
#. plural form
#. 
#. Note: most western languages will not need to change this
#: ../DistUpgrade/DistUpgradeView.py:103
#, python-format
msgid "%(str_days)s %(str_hours)s"
msgstr "%(str_days)s %(str_hours)s"

#. TRANSLATORS: you can alter the ordering of the remaining time
#. information here if you shuffle %(str_hours)s %(str_minutes)s
#. around. Make sure to keep all '$(str_*)s' in the translated string
#. and do NOT change anything appart from the ordering.
#. 
#. %(str_hours)s will be either "1 hour" or "2 hours" depending on the
#. plural form
#. 
#. Note: most western languages will not need to change this
#: ../DistUpgrade/DistUpgradeView.py:121
#, python-format
msgid "%(str_hours)s %(str_minutes)s"
msgstr "%(str_hours)s %(str_minutes)s"

#: ../DistUpgrade/DistUpgradeView.py:172
#, python-format
msgid ""
"This download will take about %s with a 40Mbit connection and about %s with "
"a 5Mbit connection."
msgstr ""

#. if we have a estimated speed, use it
#: ../DistUpgrade/DistUpgradeView.py:176
#, python-format
msgid "This download will take about %s with your connection. "
msgstr "Загрузка працягнецца прыкладна %s на Вашам далучэнні. "

#. Declare these translatable strings from the .ui files here so that
#. xgettext picks them up.
#: ../DistUpgrade/DistUpgradeView.py:270 ../data/gtkbuilder/DistUpgrade.ui.h:22
msgid "Preparing to upgrade"
msgstr "Падрыхтоўка да абнаўлення"

#: ../DistUpgrade/DistUpgradeView.py:271
msgid "Getting new software channels"
msgstr "Змена крыніц усталёўкі"

#: ../DistUpgrade/DistUpgradeView.py:272 ../data/gtkbuilder/DistUpgrade.ui.h:24
msgid "Getting new packages"
msgstr "Атрымаць новыя пакеты"

#: ../DistUpgrade/DistUpgradeView.py:273 ../data/gtkbuilder/DistUpgrade.ui.h:27
msgid "Installing the upgrades"
msgstr "Усталяваць абнаўленні"

#: ../DistUpgrade/DistUpgradeView.py:274 ../data/gtkbuilder/DistUpgrade.ui.h:26
msgid "Cleaning up"
msgstr "Ачыстка"

#: ../DistUpgrade/DistUpgradeView.py:363
#, python-format
msgid ""
"%(amount)d installed package is no longer supported by Canonical. You can "
"still get support from the community."
msgid_plural ""
"%(amount)d installed packages are no longer supported by Canonical. You can "
"still get support from the community."
msgstr[0] ""
"%(amount)d усталяваны пакет больш не падтрымліваецца Canonical. Вы можаце "
"атрымаць падтрымку ў суполцы."
msgstr[1] ""
"%(amount)d усталяваных пакета больш не падтрымліваюцца Canonical. Вы можаце "
"атрымаць падтрымку ў суполцы."
msgstr[2] ""
"%(amount)d усталяваных пакетаў больш не падтрымліваюцца Canonical. Вы можаце "
"атрымаць падтрымку ў суполцы."

#. FIXME: make those two separate lines to make it clear
#. that the "%" applies to the result of ngettext
#: ../DistUpgrade/DistUpgradeView.py:372
#, python-format
msgid "%d package is going to be removed."
msgid_plural "%d packages are going to be removed."
msgstr[0] "%d пакет будзе выдалены."
msgstr[1] "%d пакеты будзе выдалена."
msgstr[2] "%d пакетаў будзе выдалена."

#: ../DistUpgrade/DistUpgradeView.py:377
#, python-format
msgid "%d new package is going to be installed."
msgid_plural "%d new packages are going to be installed."
msgstr[0] "%d новы пакет буде ўсталяваны."
msgstr[1] "%d новых пакеты будзе ўсталявана."
msgstr[2] "%d новых пакетаў будзе ўсталявана."

#: ../DistUpgrade/DistUpgradeView.py:383
#, python-format
msgid "%d package is going to be upgraded."
msgid_plural "%d packages are going to be upgraded."
msgstr[0] "%d пакет будзе абноўлены."
msgstr[1] "%d пакеты будзе абноўлена."
msgstr[2] "%d пакетаў будзе абноўлена."

#: ../DistUpgrade/DistUpgradeView.py:391
#, python-format
msgid ""
"\n"
"\n"
"You have to download a total of %s. "
msgstr ""
"\n"
"\n"
"Усяго неабходна загрузіць %s. "

#: ../DistUpgrade/DistUpgradeView.py:396
msgid ""
"Installing the upgrade can take several hours. Once the download has "
"finished, the process cannot be canceled."
msgstr ""
"Усталёўка абнаўлення можа заняць некалькі гадзін. Пасля сканчэння спампоўкі "
"скасаваць усталёўку будзе немагчыма."

#: ../DistUpgrade/DistUpgradeView.py:400
msgid ""
"Fetching and installing the upgrade can take several hours. Once the "
"download has finished, the process cannot be canceled."
msgstr ""
"Атрыманне і ўстаноўка абнаўлення можа заняць некалькі гадзін. Як толькі "
"загрузка завершыцца, гэты працэс не можа быць адменены."

#: ../DistUpgrade/DistUpgradeView.py:405
msgid "Removing the packages can take several hours. "
msgstr "Выдаленне пакетаў можа заняць некалькі гадзін. "

#. FIXME: this should go into DistUpgradeController
#: ../DistUpgrade/DistUpgradeView.py:410
msgid "The software on this computer is up to date."
msgstr "Апраграмаванне на гэтым кампутары знаходзіцца ў актуальным стане."

#: ../DistUpgrade/DistUpgradeView.py:411
msgid ""
"There are no upgrades available for your system. The upgrade will now be "
"canceled."
msgstr "Для вашае сістэмы няма абнаўленняў. Абнаўленне будзе скасавана."

#: ../DistUpgrade/DistUpgradeView.py:427
msgid "Reboot required"
msgstr "Патрабуецца перазагрузка"

#: ../DistUpgrade/DistUpgradeView.py:428
msgid ""
"The upgrade is finished and a reboot is required. Do you want to do this now?"
msgstr ""
"Абнаўленне скончанае і патрабуецца перазагрузка. Перазагрузіцца зараз?"

#: ../DistUpgrade/DistUpgradeView.py:434
msgid "Action required"
msgstr ""

#: ../DistUpgrade/DistUpgradeView.py:435
msgid "Exit all other instances of Ubuntu WSL before continuing."
msgstr ""

#: ../DistUpgrade/DistUpgradeView.py:436
msgid "Unsaved progress may otherwise be lost."
msgstr ""

#: ../DistUpgrade/DistUpgradeView.py:439
msgid "WSL restart required"
msgstr ""

#: ../DistUpgrade/DistUpgradeView.py:440
msgid "Exit this instance of Ubuntu WSL."
msgstr ""

#: ../DistUpgrade/DistUpgradeView.py:441
msgid "The upgrade will then be complete."
msgstr ""

#: ../DistUpgrade/DistUpgradeViewText.py:82
#, python-format
msgid "Progress: [%3i%%]"
msgstr "Выкананне: [%3i%%]"

#: ../DistUpgrade/DistUpgradeViewText.py:141
msgid ""
"Please report this as a bug and include the files /var/log/dist-"
"upgrade/main.log and /var/log/dist-upgrade/apt.log in your report. The "
"upgrade has aborted.\n"
"Your original sources.list was saved in /etc/apt/sources.list.distUpgrade."
msgstr ""
"Калі ласка, паведаміце пра гэта як пра памылку і ўключаюць у сябе файлы "
"/var/log/dist-upgrade/main.log і /var/log/dist-upgrade/apt.log ў Вашым "
"дакладзе. Абнаўленне не сфармавалася.\n"
"Імя арыгінальнае sources.list быў захаваны ў "
"/etc/apt/sources.list.distUpgrade."

#: ../DistUpgrade/DistUpgradeViewText.py:165
msgid "Aborting"
msgstr "Абарваць"

#: ../DistUpgrade/DistUpgradeViewText.py:171
msgid "Demoted:\n"
msgstr "Паніжана:\n"

#: ../DistUpgrade/DistUpgradeViewText.py:178
msgid "To continue please press [ENTER]"
msgstr "Каб працягнуць, націсніце [ENTER]"

#: ../DistUpgrade/DistUpgradeViewText.py:215
#: ../DistUpgrade/DistUpgradeViewText.py:253
msgid "Details [d]"
msgstr "Дэталі [д]"

#. TRANSLATORS: the "n" is "no"
#. TRANSLATORS: first letter of a negative (no) answer
#: ../DistUpgrade/DistUpgradeViewText.py:222
#: ../DistUpgrade/DistUpgradeViewText.py:271
msgid "n"
msgstr "н"

#. TRANSLATORS: the "d" is "details"
#: ../DistUpgrade/DistUpgradeViewText.py:225
msgid "d"
msgstr "д"

#: ../DistUpgrade/DistUpgradeViewText.py:230
#, python-format
msgid "No longer supported: %s\n"
msgstr "Больш не падтрымліваецца: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:235
#, python-format
msgid "Remove: %s\n"
msgstr "Выдаліць: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:245
#, python-format
msgid "Install: %s\n"
msgstr "Усталяваць: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:250
#, python-format
msgid "Upgrade: %s\n"
msgstr "Абнавіць: %s\n"

#: ../DistUpgrade/DistUpgradeViewText.py:268
msgid "Continue [Yn] "
msgstr "Працягнуць [Тн] "

#: ../DistUpgrade/DistUpgradeViewText.py:293
msgid ""
"To finish the upgrade, a restart is required.\n"
"If you select 'y' the system will be restarted."
msgstr ""
"Каб завяршыць абнаўленне, спатрэбіцца перазагрузка.\n"
"Калі вы абярэце «т», сістэма будзе перазагружана."

#: ../DistUpgrade/GtkProgress.py:71
#, python-format
msgid "Downloading file %(current)li of %(total)li with %(speed)s/s"
msgstr "Загрузка файла %(current)li з %(total)li з хуткасцю %(speed)s/s"

#: ../DistUpgrade/GtkProgress.py:77
#, python-format
msgid "Downloading file %(current)li of %(total)li"
msgstr "Загрузка файла %(current)li з %(total)li"

#: ../data/gtkbuilder/AcquireProgress.ui.h:1
#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:7
msgid "Show progress of individual files"
msgstr "Паказваць прагрэс для асобных файлаў"

#: ../data/gtkbuilder/DistUpgrade.ui.h:1
msgid "_Cancel Upgrade"
msgstr "Ска_саваць абнаўленне"

#: ../data/gtkbuilder/DistUpgrade.ui.h:2
msgid "_Resume Upgrade"
msgstr "Пра_цягваць абнаўленне"

#: ../data/gtkbuilder/DistUpgrade.ui.h:3
msgid ""
"<b><big>Cancel the running upgrade?</big></b>\n"
"\n"
"The system could be in an unusable state if you cancel the upgrade. You are "
"strongly adviced to resume the upgrade."
msgstr ""
"<b><big>Скасаваць працэс абнаўлення?</big></b>\n"
"\n"
"Калі вы перапыніце абнаўленне, сістэма можа апынуцца ў непрацаздольным "
"стане. Настойліва рэкамендуецца працягваць абнаўленне."

#: ../data/gtkbuilder/DistUpgrade.ui.h:6
msgid "_Start Upgrade"
msgstr "За_пусціць абнаўленне"

#: ../data/gtkbuilder/DistUpgrade.ui.h:9
msgid "_Replace"
msgstr "За_мяніць"

#: ../data/gtkbuilder/DistUpgrade.ui.h:10
msgid "Difference between the files"
msgstr "Розьніца паміж файламі"

#: ../data/gtkbuilder/DistUpgrade.ui.h:11
msgid "_Report Bug"
msgstr "Па_ведаміць аб памылцы"

#: ../data/gtkbuilder/DistUpgrade.ui.h:12
msgid "_Continue"
msgstr "_Працягнуць"

#: ../data/gtkbuilder/DistUpgrade.ui.h:13
msgid "<b><big>Start the upgrade?</big></b>"
msgstr "<b><big>Пачаць абнаўленне?</big></b>"

#: ../data/gtkbuilder/DistUpgrade.ui.h:15
msgid ""
"<b><big>Restart the system to complete the upgrade</big></b>\n"
"\n"
"Please save your work before continuing."
msgstr ""
"<b><big>Перазагрузіце сістэму, каб завяршыць абнаўленне</big></b>\n"
"\n"
"Калі ласка, захавайце Вашу працу перад працягам."

#: ../data/gtkbuilder/DistUpgrade.ui.h:18
msgid "Distribution Upgrade"
msgstr "Абнавіць дыстрыбутыў"

#: ../data/gtkbuilder/DistUpgrade.ui.h:20
#, no-c-format
msgid "<b><big>Upgrading Ubuntu to version %s</big></b>"
msgstr "<b><big>Абнаўленне Ubuntu да версіі %s</big></b>"

#: ../data/gtkbuilder/DistUpgrade.ui.h:21
msgid "    "
msgstr "    "

#: ../data/gtkbuilder/DistUpgrade.ui.h:23
msgid "Setting new software channels"
msgstr "Усталёўка новых крыніц праграмнага забеспячэння"

#: ../data/gtkbuilder/DistUpgrade.ui.h:25
msgid "Restarting the computer"
msgstr "Перазапуск кампутара"

#: ../data/gtkbuilder/DistUpgrade.ui.h:28
msgid "Terminal"
msgstr "Тэрмінал"

#: ../data/gtkbuilder/ReleaseNotes.ui.h:2
msgid "_Upgrade"
msgstr "_Абнавіць"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:1
msgid ""
"<b>A new version of Ubuntu is available. Would you like to upgrade?</b>"
msgstr "<b>Даступная новая версія Ubuntu. Хочаце абнавіць?</b>"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:2
msgid "Don't Upgrade"
msgstr "Не абнаўляць"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:3
msgid "Ask Me Later"
msgstr "Спытаць пазней"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:4
msgid "Yes, Upgrade Now"
msgstr "Так, Абнавіць зараз"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:5
msgid "You have declined to upgrade to the new Ubuntu"
msgstr "Вы адмовіліся ад абнаўлення да новай версіі Ubuntu"

#: ../data/gtkbuilder/UpgradePromptDialog.ui.h:6
msgid ""
"You can upgrade at a later time by opening Software Updater and click on "
"\"Upgrade\"."
msgstr ""
"Можна абнавіць пазней, адкрыўшы прыладу абнаўлення праграм і націснуўшы "
"«Абнавіць»."

#: ../data/com.ubuntu.release-upgrader.policy.in.h:1
msgid "Perform a release upgrade"
msgstr "Выканаць абнаўленне выпуску"

#: ../data/com.ubuntu.release-upgrader.policy.in.h:2
msgid "To upgrade Ubuntu, you need to authenticate."
msgstr "Для абнаўлення Ubuntu, патрэбная аўтэнтыфікацыя."

#: ../data/com.ubuntu.release-upgrader.policy.in.h:3
msgid "Perform a partial upgrade"
msgstr "Выканаць частковае абнаўленне"

#: ../data/com.ubuntu.release-upgrader.policy.in.h:4
msgid "To perform a partial upgrade, you need to authenticate."
msgstr "Для частковага абнаўлення, вы павінны аўтарызавацца"

#: ../do-partial-upgrade:75 ../do-release-upgrade:80
msgid "Show version and exit"
msgstr "Паказаць версію і выйсці"

#: ../do-partial-upgrade:78 ../do-release-upgrade:87
msgid "Directory that contains the data files"
msgstr "Папка, якая змяшчае файлы даных"

#: ../do-partial-upgrade:81 ../do-release-upgrade:100
msgid "Run the specified frontend"
msgstr "Запусціць пазначаны інтэрфейс"

#: ../do-partial-upgrade:112
msgid "Running partial upgrade"
msgstr "Ідзе частковае абнаўленне"

#: ../do-release-upgrade:34 ../do-release-upgrade:46
msgid "Downloading the release upgrade tool"
msgstr "Спампоўваецца праграма для абнаўлення дыстрыбутыва"

#: ../do-release-upgrade:83
msgid ""
"If using the latest supported release, upgrade to the development release"
msgstr ""

#: ../do-release-upgrade:90 ../check_new_release_gtk.py:188
msgid ""
"Try upgrading to the latest release using the upgrader from $distro-proposed"
msgstr ""
"Паспрабуйце абнавіцца да самага апошняга выпуска з дапамогай $distro-proposed"

#: ../do-release-upgrade:94
msgid ""
"Run in a special upgrade mode.\n"
"Currently 'desktop' for regular upgrades of a desktop system and 'server' "
"for server systems are supported."
msgstr ""
"Запусьціць у спэцыяльным рэжыме абнаўлення.\n"
"Зараз падтрымліваецца рэгулярнае абнаўленьне для «настольных» і «серверных» "
"сістэм."

#: ../do-release-upgrade:103
msgid ""
"Check only if a new distribution release is available and report the result "
"via the exit code"
msgstr ""
"Правяраць наяўнасць новай версіі дыстрыбутыва і вярнуць вынік з дапамогай "
"кода выхаду"

#: ../do-release-upgrade:108
msgid ""
"Try the upgrade with third party mirrors and repositories enabled instead of "
"commenting them out."
msgstr ""

#: ../do-release-upgrade:114
msgid ""
"A comma-separated list of environment variables (e.g. "
"VAR1=VALUE1,VAR2=VALUE2) that should be set during the upgrade."
msgstr ""

#: ../do-release-upgrade:126
msgid "The options --devel-release and --proposed are"
msgstr "Опцыі --devel-release і --proposed"

#: ../do-release-upgrade:127
msgid "mutually exclusive. Please use only one of them."
msgstr ""
"нельга выкарыстоўваць адначасова. Калі ласка, выкарыстоўвайце толькі адзін з "
"іх."

#: ../do-release-upgrade:131
msgid "Checking for a new Ubuntu release"
msgstr "Праверка на наяўнасць новай версіі Ubuntu"

#: ../do-release-upgrade:143
msgid "Your Ubuntu release is not supported anymore."
msgstr "Ваш выпуск Ubuntu больш не падтрымліваецца."

#: ../do-release-upgrade:144
msgid ""
"For upgrade information, please visit:\n"
"%(url)s\n"
msgstr ""
"Каб атрымаць інфармацыю аб абнаўленні, наведайце:\n"
"%(url)s\n"

#: ../do-release-upgrade:159
msgid "In /etc/update-manager/release-upgrades Prompt "
msgstr ""

#: ../do-release-upgrade:160
msgid "is set to never so upgrading is not possible."
msgstr ""

#: ../do-release-upgrade:162
msgid "There is no development version of an LTS available."
msgstr ""

#: ../do-release-upgrade:163
msgid "To upgrade to the latest non-LTS development release "
msgstr ""

#: ../do-release-upgrade:164
msgid "set Prompt=normal in /etc/update-manager/release-upgrades."
msgstr ""

#: ../do-release-upgrade:166
msgid "Upgrades to the development release are only "
msgstr ""

#: ../do-release-upgrade:167
msgid "available from the latest supported release."
msgstr ""

#: ../do-release-upgrade:169
msgid "No new release found."
msgstr ""

#: ../do-release-upgrade:174
msgid "Release upgrade not possible right now"
msgstr "Абнаўленьне выпуску зараз немагчымае"

#: ../do-release-upgrade:175
#, c-format
msgid ""
"The release upgrade can not be performed currently, please try again later. "
"The server reported: '%s'"
msgstr ""
"Абнаўленне рэлізу цяпер не можа быць выканана, паспрабуйце пазней. Сервер "
"паведаміў: '%s'"

#: ../do-release-upgrade:181
#, c-format
msgid "New release '%s' available."
msgstr "Даступны новы выпуск '%s'."

#: ../do-release-upgrade:182
msgid "Run 'do-release-upgrade' to upgrade to it."
msgstr "Выканайце «do-release-upgrade», каб абнавіцца да яго."

#: ../do-release-upgrade:199
msgid ""
"Please install all available updates for your release before upgrading."
msgstr ""

#: ../do-release-upgrade:215
msgid ""
"You have not rebooted after updating a package which requires a reboot. "
"Please reboot before upgrading."
msgstr ""

#: ../check_new_release_gtk.py:88
msgid "Software Updater"
msgstr "Прылада абнаўлення пакетаў"

#: ../check_new_release_gtk.py:120
#, python-format
msgid "Ubuntu %(version)s Upgrade Available"
msgstr "Даступнае абнаўленне Ubuntu %(version)s"

#. print("don't upgrade")
#: ../check_new_release_gtk.py:151
#, python-format
msgid "You have declined the upgrade to Ubuntu %s"
msgstr "Вы адмовіліся ад абнаўлення да Ubuntu %s"

#: ../check_new_release_gtk.py:184
msgid "Check if upgrading to the latest devel release is possible"
msgstr ""
"Праверка магчымасці абнаўлення да апошняй нестабільнай версіі дыстрыбутыва"

#: ../check_new_release_gtk.py:193
msgid "Add debug output"
msgstr "Дадаць дапаможную інфармацыю"
