# Ukrainian translation for duplicity
# Copyright (c) 2013 Rosetta Contributors and Canonical Ltd 2013
# This file is distributed under the same license as the duplicity package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2013.
#
msgid ""
msgstr ""
"Project-Id-Version: duplicity\n"
"Report-Msgid-Bugs-To: FULL NAME <EMAIL@ADDRESS>\n"
"POT-Creation-Date: 2023-10-20 10:03-0500\n"
"PO-Revision-Date: 2020-04-09 22:44+0000\n"
"Last-Translator: Roman Pavlyshyn <Unknown>\n"
"Language-Team: Ukrainian <uk@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=n%10==1 && n%100!=11 ? 0 : n%10>=2 && "
"n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2;\n"
"X-Launchpad-Export-Date: 2024-03-10 12:40+0000\n"
"X-Generator: Launchpad (build 2e4955e3d556e61e2eb54acf7a827d17e9e46822)\n"

#: ../bin/duplicity:76
msgid "INT intercepted...exiting."
msgstr "Перехоплення INT...виконується вихід."

#: ../bin/duplicity:84
#, python-format
msgid "GPG error detail: %s"
msgstr "Подробиці помилки GPG: %s"

#: ../bin/duplicity:91
#, python-format
msgid "User error detail: %s"
msgstr "Відомості помилки користувача: %s"

#: ../bin/duplicity:98
#, python-format
msgid "Backend error detail: %s"
msgstr "Відомості про помилку у заглушці: %s"

#: ../duplicity/tempdir.py:157
#, python-format
msgid "Using temporary directory %s"
msgstr "Використовується тимчасовий каталог %s"

#: ../duplicity/tempdir.py:201
#, python-format
msgid "Registering (mktemp) temporary file %s"
msgstr "Реєстрація (mktemp) тимчасового файлу %s"

#: ../duplicity/tempdir.py:227
#, python-format
msgid "Registering (mkstemp) temporary file %s"
msgstr "Реєстрація (mkstemp) тимчасового файлу %s"

#: ../duplicity/tempdir.py:259
#, python-format
msgid "Forgetting temporary file %s"
msgstr "Вилучення тимчасового файлу %s"

#: ../duplicity/tempdir.py:262
#, python-format
msgid "Attempt to forget unknown tempfile %s - this is probably a bug."
msgstr ""
"Спроба вилучити невідомий тимчасовий файл %s - схоже, що це помилка у "
"програмі."

#: ../duplicity/tempdir.py:281
#, python-format
msgid "Removing still remembered temporary file %s"
msgstr "Вилучення все ще потрібного тимчасового файлу %s"

#: ../duplicity/tempdir.py:284
#, python-format
msgid "Cleanup of temporary file %s failed"
msgstr "Не вдалося очистити тимчасовий файл %s"

#: ../duplicity/tempdir.py:290
#, python-format
msgid "Cleanup of temporary directory %s failed - this is probably a bug."
msgstr ""
"Не вдалося очистити тимчасовий каталог %s - схоже, що це помилка у програмі."

#: ../duplicity/backend.py:92
#, python-format
msgid "Import of %s %s"
msgstr "Імпорт %s %s"

#: ../duplicity/backend.py:197
#, python-format
msgid "Could not initialize backend: %s"
msgstr "Не вдається ініціалізувати бекенд: %s"

#: ../duplicity/backend.py:388
#, python-format
msgid "Backtrace of previous error: %s"
msgstr "Стек викликів попередньої помилки: %s"

#: ../duplicity/backend.py:407
#, python-format
msgid "Giving up after %s attempts. %s: %s"
msgstr "Припиняємо після %s спроб. %s: %s"

#: ../duplicity/backend.py:413
#, python-format
msgid "Attempt of %s Nr. %s failed. %s: %s"
msgstr ""

#: ../duplicity/backend.py:512
#, python-format
msgid "Reading results of '%s'"
msgstr "Читання результатів «%s»"

#: ../duplicity/backend.py:539
#, python-format
msgid "Writing %s"
msgstr "Записується %s"

#: ../duplicity/backend.py:580
#, python-format
msgid "File %s not found locally after get from backend"
msgstr "Файл %s не знайдено локально після отримання з бекенду"

#: ../duplicity/manifest.py:95
#, python-format
msgid ""
"Fatal Error: Backup source host has changed.\n"
"Current hostname: %s\n"
"Previous hostname: %s"
msgstr ""
"Фатальна помилка: Вузол джерела резервної копії змінено.\n"
"Поточний вузол: %s\n"
"Попередній вузол: %s"

#: ../duplicity/manifest.py:102
msgid "Fatal Error: Backup source directory has changed.\n"
msgstr ""

#: ../duplicity/manifest.py:115
msgid ""
"Aborting because you may have accidentally tried to backup two different "
"data sets to the same remote location, or using the same archive directory.  "
"If this is not a mistake, use the --allow-source-mismatch switch to avoid "
"seeing this message"
msgstr ""
"Припинення у зв’язку з тим, що ви можете випадково спробувати створити "
"резервні копії двох відмінних наборів даних за однією адресою, у одне й те ж "
"віддалене розташування. Якщо це помилка, використайте параметр --allow-"
"source-mismatch для приховування цього повідомлення"

#: ../duplicity/manifest.py:221
#, python-format
msgid "Found manifest volume %s"
msgstr "Знайдено том маніфесту %s"

#: ../duplicity/manifest.py:228
#, python-format
msgid "Found %s volumes in manifest"
msgstr "Знайдено %s томи в маніфесті"

#: ../duplicity/manifest.py:249
msgid "Manifest file '{self.fh.base if self.fh else ''}' is corrupt: "
msgstr ""

#: ../duplicity/manifest.py:268
msgid "Manifests not equal because different volume numbers"
msgstr "Маніфести неоднакові через різні номери томів"

#: ../duplicity/manifest.py:273
msgid "Manifests not equal because volume lists differ"
msgstr "Маніфести неоднакові через різні списки томів"

#: ../duplicity/manifest.py:277
msgid "Manifests not equal because hosts or directories differ"
msgstr "Маніфести неоднакові через різні вузли та каталоги"

#: ../duplicity/manifest.py:438
msgid "Warning, found extra Volume identifier"
msgstr "Увага, знайдено додатковий ідентифікатор тому"

#: ../duplicity/manifest.py:464
msgid "Other is not VolumeInfo"
msgstr "Інший не є VolumeInfo"

#: ../duplicity/manifest.py:467
msgid "Volume numbers don't match"
msgstr "Номери томів не збігаються"

#: ../duplicity/manifest.py:470
msgid "start_indicies don't match"
msgstr "start_indicies не збігається"

#: ../duplicity/manifest.py:473
msgid "end_index don't match"
msgstr "end_index не збігається"

#: ../duplicity/manifest.py:478
msgid "Hashes don't match"
msgstr "Хеші не збігаються"

#: ../duplicity/util.py:105 ../duplicity/dup_main.py:906
#, python-format
msgid "IGNORED_ERROR: Warning: ignoring error as requested: %s: %s"
msgstr ""
"GNORED_ERROR: Увага: пропуск помилки, як було позначено у запиті: %s: %s"

#: ../duplicity/util.py:170
#, python-format
msgid "Releasing lockfile %s"
msgstr "Звільнення файлу блокування %s"

#: ../duplicity/backends/pydrivebackend.py:197
#, python-format
msgid "PyDrive backend: multiple files called '%s'."
msgstr "PyDrive backend: виклик кількох файлів «%s»"

#: ../duplicity/backends/multibackend.py:100
#, python-format
msgid "MultiBackend: Could not parse query string %s: %s "
msgstr "MultiBackend: Неможливо розібрати рядок запиту %s: %s "

#: ../duplicity/backends/multibackend.py:110
#, python-format
msgid "MultiBackend: Invalid query string %s: more than one value for %s"
msgstr ""
"MultiBackend: Неприпустимий рядок запиту %s: понад одне значення для %s"

#: ../duplicity/backends/multibackend.py:116
#, python-format
msgid "MultiBackend: Invalid query string %s: unknown parameter %s"
msgstr "MultiBackend: Неприпустимий рядок запиту %s: невідомий параметр %s"

#: ../duplicity/backends/multibackend.py:167
#: ../duplicity/backends/multibackend.py:174
#, python-format
msgid "MultiBackend: illegal value for %s: %s"
msgstr "MultiBackend: Невірне значення для %s: %s"

#: ../duplicity/backends/multibackend.py:186
#, python-format
msgid "MultiBackend: Url %s"
msgstr "MultiBackend: Url %s"

#: ../duplicity/backends/multibackend.py:189
#, python-format
msgid "MultiBackend: Could not load config file %s: %s "
msgstr "MultiBackend: Неможливо завантажити файл конфігурації %s: %s "

#: ../duplicity/backends/multibackend.py:196
#, python-format
msgid "MultiBackend: use store %s"
msgstr "MultiBackend: використовувати сховище %s"

#: ../duplicity/backends/multibackend.py:200
#, python-format
msgid "MultiBackend: set env %s = %s"
msgstr "MultiBackend: задати змінну середовища %s = %s"

#: ../duplicity/backends/multibackend.py:214
#, python-format
msgid "Multibackend: register affinity for prefix %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:257
#, python-format
msgid "MultiBackend: _put: write to store #%s (%s)"
msgstr "MultiBackend: _put: запис до сховища #%s (%s)"

#: ../duplicity/backends/multibackend.py:272
#, python-format
msgid ""
"MultiBackend: failed to write to store #%s (%s), try #%s, Exception: %s"
msgstr ""
"MultiBackend: не вдалося записати до сховища #%s (%s), спроба #%s, Виняток: "
"%s"

#: ../duplicity/backends/multibackend.py:286
#, python-format
msgid "MultiBackend: failed to write %s. Aborting process."
msgstr "MultiBackend: збій запису %s. Переривання процесу."

#: ../duplicity/backends/multibackend.py:294
#, python-format
msgid ""
"MultiBackend: failed to write %s. Tried all backing stores and none succeeded"
msgstr ""
"MultiBackend: збій запису %s. Спроба опитати усі сховища резервних копій і "
"жодного успіху."

#: ../duplicity/backends/multibackend.py:315
#, python-format
msgid "MultiBackend: failed to get %s to %s from %s"
msgstr "MultiBackend: не вдалося отримати %s до %s з %s"

#: ../duplicity/backends/multibackend.py:320
#, python-format
msgid ""
"MultiBackend: failed to get %s. Tried all backing stores and none succeeded"
msgstr ""
"MultiBackend: не вдалося отримати %s. Спроба опитати усі сховища резервних "
"копій і жодного успіху."

#: ../duplicity/backends/multibackend.py:330
#, python-format
msgid "MultiBackend: %s: %d files"
msgstr ""

#: ../duplicity/backends/multibackend.py:334
msgid "Exception during list of {s.backend.parsed_url.strip_auth()}: "
msgstr ""

#: ../duplicity/backends/multibackend.py:342
#, python-format
msgid "MultiBackend: combined list: %s"
msgstr "MultiBackend: комбінований список: %s"

#: ../duplicity/backends/multibackend.py:374
#: ../duplicity/backends/multibackend.py:404
#, python-format
msgid ""
"MultiBackend: failed to delete %s. Tried all backing stores and none "
"succeeded"
msgstr ""
"MultiBackend: не вдалося видалити %s. Спроба опитати усі сховища резервних "
"копій і жодного успіху."

#: ../duplicity/backends/giobackend.py:108
#, python-format
msgid "Connection failed, please check your password: %s"
msgstr "Не вдалося під’єднатися, перевірте пароль: %s"

#: ../duplicity/backends/onedrivebackend.py:90
#, python-format
msgid "Attempt of initialize_oauth2_session Nr. %s failed. %s: %s"
msgstr ""

#: ../duplicity/backends/webdavbackend.py:67
msgid "Missing socket or ssl python modules."
msgstr "Відсутні python-модулі socket або ssl ."

#: ../duplicity/backends/webdavbackend.py:87
#, python-format
msgid "Cacert database file '%s' is not readable."
msgstr "Файл бази даних Cacert «%s» недоступний для читання."

#: ../duplicity/backends/webdavbackend.py:149
#, python-format
msgid "Using WebDAV host %s port %s"
msgstr "Використання вузла WebDAV %s порт %s"

#: ../duplicity/backends/webdavbackend.py:150
#, python-format
msgid "Using WebDAV directory %s"
msgstr "Використання WebDAV %s"

#: ../duplicity/backends/webdavbackend.py:180
#, python-format
msgid "WebDAV create connection on '%s'"
msgstr "WebDAV: створити з'єднання «%s»"

#: ../duplicity/backends/webdavbackend.py:191
#, python-format
msgid "WebDAV Unknown URI scheme: %s"
msgstr "WebDAV: Невідома схема URI: %s"

#: ../duplicity/backends/webdavbackend.py:210
#, python-format
msgid "WebDAV %s %s request with headers: %s "
msgstr "WebDAV: %s %s запит із заголовками: %s "

#: ../duplicity/backends/webdavbackend.py:211
#: ../duplicity/backends/webdavbackend.py:234
#, python-format
msgid "WebDAV data length: %s "
msgstr "WebDAV: довжина даних: %s "

#: ../duplicity/backends/webdavbackend.py:214
#, python-format
msgid "WebDAV response status %s with reason '%s'."
msgstr "WebDAV: стан відповіді %s з причиною «%s»."

#: ../duplicity/backends/webdavbackend.py:220
#, python-format
msgid "WebDAV redirect to: %s "
msgstr "WebDAV: переспрямування на: %s "

#: ../duplicity/backends/webdavbackend.py:222
msgid "WebDAV redirected 10 times. Giving up."
msgstr "WebDAV: переспрямовано 10 разів. Припиняємо."

#: ../duplicity/backends/webdavbackend.py:227
msgid "WebDAV missing location header in redirect response."
msgstr "WebDAV: відсутній заголовок місця у відповіді переспрямування."

#: ../duplicity/backends/webdavbackend.py:232
msgid "WebDAV retry request with authentification headers."
msgstr "WebDAV запит повтору з заголовками автентифікації"

#: ../duplicity/backends/webdavbackend.py:233
#, python-format
msgid "WebDAV %s %s request2 with headers: %s "
msgstr "WebDAV %s %s запит2 із заголовками: %s "

#: ../duplicity/backends/webdavbackend.py:237
#, python-format
msgid "WebDAV response2 status %s with reason '%s'."
msgstr "WebDAV response2 стан %s з причиною «%s»."

#: ../duplicity/backends/webdavbackend.py:256
msgid ""
"python-kerberos needed to use kerberos                           "
"authorization, falling back to basic auth."
msgstr ""
"python-kerberos потребував авторизації kerberos, переходимо до резервної "
"basic-авторизації."

#: ../duplicity/backends/webdavbackend.py:264
#, python-format
msgid ""
"Kerberos authorization failed: %s.                          Falling back to "
"basic auth."
msgstr ""
"Kerberos-авторизація завершилася помилкою: %s.                          "
"Переходимо до резервної basic-авторизації."

#: ../duplicity/backends/webdavbackend.py:365
#, python-format
msgid "Creating missing directory %s"
msgstr "Створення відсутнього каталогу %s"

#: ../duplicity/backends/webdavbackend.py:369
#, python-format
msgid "WebDAV MKCOL %s failed: %s %s"
msgstr "WebDAV MKCOL %s невдале: %s %s"

#: ../duplicity/backends/webdavbackend.py:381
#, python-format
msgid "WebDAV path decoding and translation: %s -> %s"
msgstr "WebDAV: декодування шляху та переклад: %s -> %s"

#: ../duplicity/backends/webdavbackend.py:421
#, python-format
msgid "WebDAV GET Bad status code %s reason %s."
msgstr "WebDAV: запит GET - невірний код стану %s, причина %s."

#: ../duplicity/backends/webdavbackend.py:442
#, python-format
msgid "WebDAV PUT Bad status code %s reason %s."
msgstr "WebDAV: запит PUT - невірний код стану %s, причина %s."

#: ../duplicity/backends/webdavbackend.py:461
#, python-format
msgid "WebDAV DEL Bad status code %s reason %s."
msgstr "WebDAV: запит DEL - невірний код стану %s причина %s."

#. Used in usage help to represent a Unix-style path name. Example:
#. --archive-dir <path>
#: ../duplicity/cli_data.py:102 ../duplicity/cli_data.py:162
#: ../duplicity/cli_data.py:196 ../duplicity/cli_data.py:243
#: ../duplicity/cli_data.py:346 ../duplicity/cli_data.py:364
#: ../duplicity/cli_data.py:514 ../duplicity/cli_data.py:696
#: ../duplicity/cli_data.py:900
msgid "path"
msgstr "шлях"

#: ../duplicity/cli_data.py:115
msgid "Hot|Cool|Archive"
msgstr "Гарячий|Холодний|Архів"

#. Used in usage help to represent a desired number of
#. something. Example:
#. --num-retries <number>
#: ../duplicity/cli_data.py:120 ../duplicity/cli_data.py:126
#: ../duplicity/cli_data.py:134 ../duplicity/cli_data.py:168
#: ../duplicity/cli_data.py:422 ../duplicity/cli_data.py:438
#: ../duplicity/cli_data.py:485 ../duplicity/cli_data.py:502
#: ../duplicity/cli_data.py:508 ../duplicity/cli_data.py:526
#: ../duplicity/cli_data.py:592 ../duplicity/cli_data.py:600
#: ../duplicity/cli_data.py:652 ../duplicity/cli_data.py:733
#: ../duplicity/cli_data.py:887
msgid "number"
msgstr "кількість"

#. Used in usage help. Example:
#. --timeout <seconds>
#: ../duplicity/cli_data.py:146 ../duplicity/cli_data.py:703
#: ../duplicity/cli_data.py:913
msgid "seconds"
msgstr "секунди"

#. Used in usage help to represent an ID for a GnuPG key. Example:
#. --encrypt-key <gpg_key_id>
#: ../duplicity/cli_data.py:184 ../duplicity/cli_data.py:190
#: ../duplicity/cli_data.py:358 ../duplicity/cli_data.py:659
#: ../duplicity/cli_data.py:879
msgid "gpg-key-id"
msgstr "ідент-ключ-gpg"

#. Used in usage help to represent a "glob" style pattern for
#. matching one or more files, as described in the documentation.
#. Example:
#. --exclude <shell_pattern>
#: ../duplicity/cli_data.py:201 ../duplicity/cli_data.py:386
#: ../duplicity/cli_data.py:918
msgid "shell_pattern"
msgstr "шаблон_оболонки"

#. Used in usage help to represent the name of a file. Example:
#. --log-file <filename>
#: ../duplicity/cli_data.py:213 ../duplicity/cli_data.py:219
#: ../duplicity/cli_data.py:279 ../duplicity/cli_data.py:392
#: ../duplicity/cli_data.py:876
msgid "filename"
msgstr "ім'я файлу"

#. Used in usage help to represent a time spec for a previous
#. point in time, as described in the documentation. Example:
#. duplicity remove-older-than time [options] target_url
#: ../duplicity/cli_data.py:225 ../duplicity/cli_data.py:539
#: ../duplicity/cli_data.py:944
msgid "time"
msgstr "час"

#: ../duplicity/cli_data.py:237 ../duplicity/cli_data.py:398
msgid "regex"
msgstr ""

#: ../duplicity/cli_data.py:340
msgid "interval"
msgstr ""

#. Used in usage help. (Should be consistent with the "Options:"
#. header.) Example:
#. duplicity [full|incremental] [options] source_path target_url
#: ../duplicity/cli_data.py:352 ../duplicity/cli_data.py:496
#: ../duplicity/cli_data.py:545 ../duplicity/cli_data.py:675
#: ../duplicity/cli_data.py:891 ../duplicity/argparse311.py:1671
msgid "options"
msgstr "параметри"

#: ../duplicity/cli_data.py:381
msgid "imap_mailbox"
msgstr "скринька_imap"

#: ../duplicity/cli_data.py:406
msgid ""
"If set, an extra file with statistics in json format will be stored with "
"each backup. It includes the statistics printed out on stdout by default. "
"With 'collection-status' it returs these stats."
msgstr ""

#: ../duplicity/cli_data.py:413
msgid "file_descriptor"
msgstr "дескриптор_файлу"

#: ../duplicity/cli_data.py:415
msgid "log_filename"
msgstr ""

#: ../duplicity/cli_data.py:444
msgid "backup name"
msgstr "назва резервної копії"

#: ../duplicity/cli_data.py:551
msgid "s3_endpoint_url"
msgstr ""

#: ../duplicity/cli_data.py:619
msgid "s3_kms_key_id"
msgstr ""

#: ../duplicity/cli_data.py:625
msgid "s3_kms_grant"
msgstr ""

#: ../duplicity/cli_data.py:631
msgid "s3_region_name"
msgstr ""

#: ../duplicity/cli_data.py:637
msgid "policy"
msgstr "політика"

#. noun
#: ../duplicity/cli_data.py:642 ../duplicity/cli_data.py:647
#: ../duplicity/cli_data.py:865
msgid "command"
msgstr "команда"

#: ../duplicity/cli_data.py:682
msgid "pem formatted bundle of certificate authorities"
msgstr "pem-форматована збірка центрів сертифікації"

#: ../duplicity/cli_data.py:687
msgid "path to a folder with certificate authority files"
msgstr "шлях до теки з файлами центрів сертифікації"

#. abbreviation for "character" (noun)
#: ../duplicity/cli_data.py:709 ../duplicity/cli_data.py:863
msgid "char"
msgstr "символ"

#: ../duplicity/cli_data.py:722
msgid "verb"
msgstr ""

#: ../duplicity/cli_data.py:740
msgid "extra headers for Webdav, like 'Cookie,name=value'"
msgstr ""

#. Used in usage help to represent a Unix-style path name. Example:
#. rsync://user[:password]@other_host[:port]//absolute_path
#: ../duplicity/cli_data.py:854
msgid "absolute_path"
msgstr "повний_шлях"

#. Used in usage help. Example:
#. tahoe://alias/some_dir
#: ../duplicity/cli_data.py:857
msgid "alias"
msgstr "псевдонім"

#. Used in help to represent a "bucket name" for Amazon Web
#. Services' Simple Storage Service (S3). Example:
#. s3://other.host/bucket_name[/prefix]
#: ../duplicity/cli_data.py:861
msgid "bucket_name"
msgstr "bucket_name"

#. Used in usage help to represent the name of a container in
#. Amazon Web Services' Cloudfront. Example:
#. cf+http://container_name
#: ../duplicity/cli_data.py:869
msgid "container_name"
msgstr "container_name"

#. noun
#: ../duplicity/cli_data.py:871
msgid "count"
msgstr "кількість"

#. Used in usage help to represent the name of a file directory
#: ../duplicity/cli_data.py:873
msgid "directory"
msgstr "каталог"

#. Used in usage help, e.g. to represent the name of a code
#. module. Example:
#. rsync://user[:password]@other.host[:port]::/module/some_dir
#: ../duplicity/cli_data.py:883
msgid "module"
msgstr "модуль"

#. Used in usage help to represent an internet hostname. Example:
#. ftp://user[:password]@other.host[:port]/some_dir
#: ../duplicity/cli_data.py:894
msgid "other.host"
msgstr "other.host"

#. Used in usage help. Example:
#. ftp://user[:password]@other.host[:port]/some_dir
#: ../duplicity/cli_data.py:897
msgid "password"
msgstr "пароль"

#. Used in usage help to represent a TCP port number. Example:
#. ftp://user[:password]@other.host[:port]/some_dir
#: ../duplicity/cli_data.py:903
msgid "port"
msgstr "порт"

#. Used in usage help. This represents a string to be used as a
#. prefix to names for backup files created by Duplicity. Example:
#. s3://other.host/bucket_name[/prefix]
#: ../duplicity/cli_data.py:907
msgid "prefix"
msgstr "префікс"

#. Used in usage help to represent a Unix-style path name. Example:
#. rsync://user[:password]@other.host[:port]/relative_path
#: ../duplicity/cli_data.py:910
msgid "relative_path"
msgstr "відносний_шлях"

#. Used in usage help to represent the name of a single file
#. directory or a Unix-style path to a directory. Example:
#. file:///some_dir
#: ../duplicity/cli_data.py:922
msgid "some_dir"
msgstr "деякий_каталог"

#. Used in usage help to represent the name of a single file
#. directory or a Unix-style path to a directory where files will be
#. coming FROM. Example:
#. duplicity [full|incremental] [options] source_path target_url
#: ../duplicity/cli_data.py:927
msgid "source_path"
msgstr ""

#. Used in usage help to represent a URL files will be coming
#. FROM. Example:
#. duplicity [restore] [options] source_url target_dir
#: ../duplicity/cli_data.py:931
msgid "source_url"
msgstr "джерельна_url"

#. Used in usage help to represent the name of a single file
#. directory or a Unix-style path to a directory. where files will be
#. going TO. Example:
#. duplicity [restore] [options] source_url target_dir
#: ../duplicity/cli_data.py:936
msgid "target_dir"
msgstr "каталог_призначення"

#. Used in usage help to represent a URL files will be going TO.
#. Example:
#. duplicity [full|incremental] [options] source_path target_url
#: ../duplicity/cli_data.py:940
msgid "target_url"
msgstr "url_призначення"

#. Used in usage help to represent a user name (i.e. login).
#. Example:
#. ftp://user[:password]@other.host[:port]/some_dir
#: ../duplicity/cli_data.py:948
msgid "user"
msgstr "користувач"

#. account id for b2. Example: b2://account_id@bucket/
#: ../duplicity/cli_data.py:950
msgid "account_id"
msgstr "account_id"

#. application_key for b2.
#. Example: b2://account_id:application_key@bucket/
#: ../duplicity/cli_data.py:953
msgid "application_key"
msgstr "application_key"

#. remote name for rclone.
#. Example: rclone://remote:/some_dir
#: ../duplicity/cli_data.py:956 ../duplicity/dup_collections.py:568
msgid "remote"
msgstr "віддалено"

#: ../duplicity/cli_data.py:960
msgid "Backends and their URL formats:"
msgstr "Заглушки та формат їх URL:"

#: ../duplicity/diffdir.py:102 ../duplicity/diffdir.py:401
#, python-format
msgid "Error %s getting delta for %s"
msgstr "Помилка %s при отриманні відмінностей для %s"

#: ../duplicity/diffdir.py:116
#, python-format
msgid "Getting delta of %s and %s"
msgstr "Отримання дельти %s та %s"

#: ../duplicity/diffdir.py:160
#, python-format
msgid "A %s"
msgstr "Д %s"

#: ../duplicity/diffdir.py:168
#, python-format
msgid "M %s"
msgstr "M %s"

#: ../duplicity/diffdir.py:191
#, python-format
msgid "Comparing %s and %s"
msgstr "Порівняння %s та %s"

#: ../duplicity/diffdir.py:204
#, python-format
msgid "D %s"
msgstr "В %s"

#: ../duplicity/librsync.py:194
msgid ""
"basis_file must be a (true) file or an object whose file attribute is the "
"underlying true file object"
msgstr ""
"basis_file має бути (справжнім) файлом чи об'єктом, файловий атрибут якого є "
"справжним об'єктом файлу, який береться за основу"

#: ../duplicity/dup_time.py:54
#, python-format
msgid ""
"Bad interval string \"%s\"\n"
"\n"
"Intervals are specified like 2Y (2 years) or 2h30m (2.5 hours).  The\n"
"allowed special characters are s, m, h, D, W, M, and Y.  See the man\n"
"page for more information."
msgstr ""
"Рядок з неприпустимим інтервалом «%s»\n"
"\n"
"Інтервали вказуються на подобі 2Y (2 роки) або 2h30m (2.5 години).\n"
"Припустимі особливі символи s (с.), m (хв.), h (год.), D(Д.), W (Т.), M (М.) "
"и Y (Р.).\n"
"Зверніться до посібника користувача (man) для отримання додаткових "
"відомостей."

#: ../duplicity/dup_time.py:63
#, python-format
msgid ""
"Bad time string \"%s\"\n"
"\n"
"The acceptible time strings are intervals (like \"3D64s\"), w3-datetime\n"
"strings, like \"2002-04-26T04:22:01-07:00\" (strings like\n"
"\"2002-04-26T04:22:01\" are also acceptable - duplicity will use the\n"
"current time zone), or ordinary dates like 2/4/1997 or 2001-04-23\n"
"(various combinations are acceptable, but the month always precedes\n"
"the day)."
msgstr ""
"Рядок з неприпустимим часом «%s»\n"
"\n"
"Допускається вказування інтервалів часу (наприклад «3D64s»), рядка\n"
"дати/часу формату w3, наприклад «2002-04-26T04:22:01-07:00» (рядка типу\n"
"«2002-04-26T04:22:01» також припустимі - duplicity буде використовувати\n"
"поточну часову зону) або звичайні дати, наприклад 2/4/1997 або 2001-04-23\n"
"(припустимі різноманітні комбінації, але місяць завжди передує дню)."

#: ../duplicity/cli_main.py:190
msgid ""
"No valid action found. Will imply 'backup' because a path source was given "
"and target is a url location."
msgstr ""

#: ../duplicity/cli_main.py:198
msgid ""
"No valid action found. Will imply 'restore' because url source was given and "
"target is a local path."
msgstr ""

#: ../duplicity/cli_main.py:205
#, python-brace-format
msgid "Invalid '{remainder[0]}' action and cannot be implied from the "
msgstr ""

#: ../duplicity/cli_main.py:269
#, python-brace-format
msgid "GPG binary is {config.gpg_binary}, version {gpg_version}"
msgstr ""

#: ../duplicity/cli_main.py:305
#, python-brace-format
msgid "Using archive dir: {config.archive_dir_path.uc_name}"
msgstr ""

#: ../duplicity/cli_main.py:306
#, python-brace-format
msgid "Using backup name: {config.backup_name}"
msgstr ""

#: ../duplicity/dup_main.py:113
msgid "Reuse configured PASSPHRASE as SIGN_PASSPHRASE"
msgstr "Повторне використання налаштованого PASSPHRASE як SIGN_PASSPHRASE"

#: ../duplicity/dup_main.py:124
msgid "Reuse configured SIGN_PASSPHRASE as PASSPHRASE"
msgstr "Повторне використання налаштованого SIGN_PASSPHRASE як PASSPHRASE"

#: ../duplicity/dup_main.py:168
msgid "PASSPHRASE variable not set, asking user."
msgstr "Змінна PASSPHRASE не призначена, виконується запит користувача."

#: ../duplicity/dup_main.py:193
msgid "Retype passphrase for signing key to confirm: "
msgstr "Уведіть повторно кодову фразу для підписуючого ключа: "

#: ../duplicity/dup_main.py:195
msgid "Retype passphrase for decryption to confirm: "
msgstr ""

#: ../duplicity/dup_main.py:199
msgid "First and second passphrases do not match!  Please try again."
msgstr ""
"Перша та друга кодова фраза не збігаються! Будь-ласка, повторіть знову."

#: ../duplicity/dup_main.py:210
msgid ""
"Cannot use empty passphrase with symmetric encryption!  Please try again."
msgstr ""
"Неможливо використовувати порожню кодову фразу з симетричним шифруванням! "
"Будь-ласка, повторіть знову."

#: ../duplicity/dup_main.py:270
#, python-format
msgid ""
"File %s complete in backup set.\n"
"Continuing restart on file %s."
msgstr ""
"Файл %s вже є у наборі резервного копіювання.\n"
"Продовження перезапуску на файлі %s."

#: ../duplicity/dup_main.py:280
#, python-format
msgid ""
"File %s missing in backup set.\n"
"Continuing restart on file %s."
msgstr ""
"Файл %s відсутній у наборі резервного копіювання.\n"
"Продовження перезапуску на файлі %s."

#: ../duplicity/dup_main.py:335
#, python-format
msgid "%s Remote filesize %d for %s does not match local size %d, retrying."
msgstr ""

#: ../duplicity/dup_main.py:342
#, python-format
msgid "File %s was corrupted during upload."
msgstr "Файл %s було пошкоджено під час вивантаження."

#: ../duplicity/dup_main.py:382
msgid ""
"Restarting backup, but current encryption settings do not match original "
"settings"
msgstr ""
"Перезапуск резервного копіювання, але налаштування поточного шифрування не "
"відповідають вихідним налаштуванням"

#: ../duplicity/dup_main.py:404
msgid "Skipping encryption validation due to glacier/deep storage"
msgstr ""

#: ../duplicity/dup_main.py:408
#, python-format
msgid "Restarting after volume %s, file %s, block %s"
msgstr "Відновлення після тому %s, файлу %s, блоку %s"

#: ../duplicity/dup_main.py:471
msgid "Skipped volume upload, as effectivly nothing has changed"
msgstr ""

#: ../duplicity/dup_main.py:485
#, python-format
msgid "Processed volume %d"
msgstr "Опрацювання тому %d"

#: ../duplicity/dup_main.py:653
msgid ""
"Fatal Error: Unable to start incremental backup.  Old signatures not found "
"and incremental specified"
msgstr ""
"Фатальна помилка: Не вдалося почати покрокове резервне копіювання. Старої "
"сигнатури не знайдено та вказаний покроковий режим"

#: ../duplicity/dup_main.py:659
msgid "No signatures found, switching to full backup."
msgstr "Сигнатури не знайдено, перемикання на повну резервну копію."

#: ../duplicity/dup_main.py:673
msgid "Backup Statistics"
msgstr "Статистика резервного копіювання"

#: ../duplicity/dup_main.py:813
#, python-format
msgid "%s not found in archive - no files restored."
msgstr "%s не знайдено в архіві — жодного файлу не відновлено."

#: ../duplicity/dup_main.py:817
msgid "No files found in archive - nothing restored."
msgstr "Жодних файлів в архіві не знайдено — нічого не відновлено."

#: ../duplicity/dup_main.py:853
#, python-format
msgid "Processed volume %d of %d"
msgstr "Оброблено том %d з %d"

#: ../duplicity/dup_main.py:896
#, python-format
msgid "Invalid data - %s hash mismatch for file:"
msgstr "Неприпустимі дані - %s hash не відповідає файлу:"

#: ../duplicity/dup_main.py:898
#, python-format
msgid "Calculated hash: %s"
msgstr "Обчислений хеш: %s"

#: ../duplicity/dup_main.py:899
#, python-format
msgid "Manifest hash: %s"
msgstr "Хеш маніфесту: %s"

#: ../duplicity/dup_main.py:952
#, python-format
msgid "Volume was signed by key %s, not %s"
msgstr "Том було підписано ключем %s, а не %s"

#: ../duplicity/dup_main.py:984
#, python-format
msgid "Verify complete: %s, %s."
msgstr "Перевірку закінчено: %s, %s."

#: ../duplicity/dup_main.py:985
#, python-format
msgid "%d file(s) compared"
msgstr ""

#: ../duplicity/dup_main.py:985
#, python-format
msgid "%d difference(s) found"
msgstr ""

#: ../duplicity/dup_main.py:1004
msgid "No extraneous files found, nothing deleted in cleanup."
msgstr "Сторонніх файлів не знайдено, під час прибирання нічого не видалено."

#: ../duplicity/dup_main.py:1019
msgid "Found the following file(s) to delete:"
msgstr ""

#: ../duplicity/dup_main.py:1023
msgid "Run duplicity again with the --force option to actually delete."
msgstr "Запустіть duplicity ще раз з ключем --force щоб вилучити на справді."

#: ../duplicity/dup_main.py:1069
msgid "There are backup set(s) at time(s):"
msgstr "Є резервні копії за такі дати:"

#: ../duplicity/dup_main.py:1071
msgid "Which can't be deleted because newer sets depend on them."
msgstr "Які не може бути вилучено через нові набори, що залежать від них."

#: ../duplicity/dup_main.py:1078
msgid ""
"Current active backup chain is older than specified time.  However, it will "
"not be deleted.  To remove all your backups, manually purge the repository."
msgstr ""
"Поточний активний ланцюжок резервних копій старіший ніж вказаний час. Втім "
"його не буде вилучено. Щоб вилучити усі резервні копії, вручну очистіть "
"сховище."

#: ../duplicity/dup_main.py:1096
msgid "No old backup sets found, nothing deleted."
msgstr "Старих резервних копій не знайдено, нічого не вилучено."

#: ../duplicity/dup_main.py:1099
msgid "Deleting backup chain(s) at time:"
msgstr ""

#: ../duplicity/dup_main.py:1108
#, python-format
msgid "Deleting any incremental signature chain rooted at %s"
msgstr ""
"Видалення будь-якого покрокового ланцюжка сигнатур, що починається на %s"

#: ../duplicity/dup_main.py:1110
#, python-format
msgid "Deleting any incremental backup chain rooted at %s"
msgstr ""
"Видалення будь-якого покрокового ланцюжка резервних копій, що починається на "
"%s"

#: ../duplicity/dup_main.py:1113
#, python-format
msgid "Deleting complete signature chain %s"
msgstr "Вилучення повного ланцюжка сигнатур %s"

#: ../duplicity/dup_main.py:1115
#, python-format
msgid "Deleting complete backup chain %s"
msgstr "Вилучення повного ланцюжка резервних копій %s"

#: ../duplicity/dup_main.py:1122
msgid "Found old backup chain(s) at the following time:"
msgstr ""

#: ../duplicity/dup_main.py:1126
msgid "Rerun command with --force option to actually delete."
msgstr ""
"Знову запустіть команду разом з параметром --force для фактичного видалення."

#: ../duplicity/dup_main.py:1229
#, python-format
msgid "Deleting local %s (not authoritative at backend)."
msgstr ""
"Вилучення локального %s (недостатньо надійний у внутрішньому інтерфейсі)."

#: ../duplicity/dup_main.py:1233
#, python-format
msgid "Unable to delete %s: %s"
msgstr "Неможливо вилучити %s: %s"

#: ../duplicity/dup_main.py:1267 ../duplicity/dup_temp.py:296
#, python-format
msgid "Failed to read %s: %s"
msgstr "Не вдалося прочитати %s: %s"

#: ../duplicity/dup_main.py:1279
#, python-format
msgid "Copying %s to local cache."
msgstr "Копіюється %s у локальний кеш."

#: ../duplicity/dup_main.py:1327
msgid "Local and Remote metadata are synchronized, no sync needed."
msgstr ""
"Локальні та вилучені метадані синхронізовано, синхронізація не потрібна."

#: ../duplicity/dup_main.py:1332
msgid "Synchronizing remote metadata to local cache..."
msgstr ""
"Синхронізація вилучених метаданих з локальними тимчасовими файлами..."

#: ../duplicity/dup_main.py:1346
msgid "Sync would copy the following from remote to local:"
msgstr "Синхронізація скопіює це з вилученого місця у локальне:"

#: ../duplicity/dup_main.py:1352
msgid "Sync would remove the following spurious local files:"
msgstr "Синхронізація вилучить наступні невідомі файли:"

#: ../duplicity/dup_main.py:1398
msgid "Unable to get free space on temp."
msgstr ""
"Не вдалося визначити об’єм доступного простору у тимчасовому каталозі."

#: ../duplicity/dup_main.py:1405
#, python-format
msgid "Temp space has %d available, backup needs approx %d."
msgstr ""
"У тимчасовому каталозі доступно %d, для резервного копіювання потрібно "
"приблизно %d."

#: ../duplicity/dup_main.py:1409
#, python-format
msgid "Temp has %d available, backup will use approx %d."
msgstr ""
"У тимчасовому каталозі доступно %d, для резервного копіювання буде "
"використано приблизно %d."

#: ../duplicity/dup_main.py:1416
msgid "Unable to get max open files."
msgstr "Не вдалося визначити максимальну кількість відкритих файлів."

#: ../duplicity/dup_main.py:1421
#, python-format
msgid ""
"Max open files of %s is too low, should be >= 1024.\n"
"Use 'ulimit -n 1024' or higher to correct.\n"
msgstr ""
"Максимальна кількість відкритих файлів %s надто мала, Має бути >= 1024.\n"
"Використайте «ulimit -n 1024» або вище, щоб виправити.\n"

#: ../duplicity/dup_main.py:1477
msgid ""
"RESTART: The first volume failed to upload before termination.\n"
"         Restart is impossible...starting backup from beginning."
msgstr ""
"ПЕРЕЗАПУСК: Помилка вивантаження першого тому перед закінченням роботи.\n"
"         Перезапуск неможливий...виконання резервного копіювання з початку."

#: ../duplicity/dup_main.py:1487
#, python-format
msgid ""
"RESTART: Volumes %d to %d failed to upload before termination.\n"
"         Restarting backup at volume %d."
msgstr ""
"ПЕРЕЗАПУСК: Помилка вивантаження томів %d дo %d перед закінченням роботи.\n"
"Перезапуск резервного копіювання у томі %d."

#: ../duplicity/dup_main.py:1498
#, python-format
msgid ""
"RESTART: Impossible backup state: manifest has %d vols, remote has %d vols.\n"
"         Restart is impossible ... duplicity will clean off the last "
"partial\n"
"         backup then restart the backup from the beginning."
msgstr ""
"ПЕРЕЗАПУСК: Неможливий стан резервної копії: маніфест містить %d томів, "
"віддалений містить %d томів.\n"
"         Перезапуск неможливий ... duplicity проведе очищення останньої "
"частини\n"
"         резервної копії, потім запустить резервне копіювання з початку."

#: ../duplicity/dup_main.py:1523
msgid ""
"PYTHONOPTIMIZE in the environment causes duplicity to fail to\n"
"recognize its own backups.  Please remove PYTHONOPTIMIZE from\n"
"the environment and rerun the backup.\n"
"\n"
"See https://bugs.launchpad.net/duplicity/+bug/931175\n"
msgstr ""

#: ../duplicity/dup_main.py:1549
#, python-format
msgid "Acquiring lockfile %s"
msgstr "Отримання файлу блокування %s"

#: ../duplicity/dup_main.py:1609
#, python-brace-format
msgid "Last {action} backup left a partial set, restarting."
msgstr ""

#: ../duplicity/dup_main.py:1613
#, python-brace-format
msgid "Cleaning up previous partial {action} backup set, restarting."
msgstr ""

#: ../duplicity/dup_main.py:1627
msgid "Last full backup date: none"
msgstr "Час останньої повної резервної копії: немає"

#: ../duplicity/dup_main.py:1634
msgid "Last full backup is too old, forcing full backup"
msgstr ""
"Остання повна резервна копія надто стара, буде зроблено повну резервну копію"

#: ../duplicity/dup_main.py:1690
msgid ""
"When using symmetric encryption, the signing passphrase must equal the "
"encryption passphrase."
msgstr ""
"При використанні симетричного шифрування кодова фраза для підпису повинна "
"збігатися з кодовою фразою для шифрування."

#: ../duplicity/asyncscheduler.py:259
#, python-format
msgid "task execution done (success: %s)"
msgstr "закінчено виконання завдання (успіх: %s)"

#: ../duplicity/gpginterface.py:694
#, python-brace-format
msgid "GPG process {process.pid} terminated before wait()"
msgstr ""

#: ../duplicity/robust.py:84
#, python-format
msgid "Error listing directory %s"
msgstr "Помилка переліку каталогу %s"

#: ../duplicity/dup_collections.py:203 ../duplicity/dup_collections.py:212
#, python-format
msgid "BackupSet.delete: missing %s"
msgstr "BackupSet.delete: відсутній %s"

#: ../duplicity/dup_collections.py:238
msgid "Fatal Error: No manifests found for most recent backup"
msgstr "Фатальна помилка: відсутні маніфести для недавньої резервної копії"

#: ../duplicity/dup_collections.py:251
msgid ""
"Fatal Error: Remote manifest does not match local one.  Either the remote "
"backup set or the local archive directory has been corrupted."
msgstr ""
"Фатальна помилка: Вилучений маніфест не відповідає локальному. Пошкоджено "
"або віддалений набір резервного копіювання або тека локального архіву."

#: ../duplicity/dup_collections.py:259
#, python-format
msgid "Error processing remote manifest (%s): %s"
msgstr "Помилка обробки віддаленого маніфесту (%s): %s"

#: ../duplicity/dup_collections.py:268
msgid "Fatal Error: Neither remote nor local manifest is readable."
msgstr ""
"Фатальна помилка: Немає доступу до читання віддаленого та локального "
"маніфесту."

#: ../duplicity/dup_collections.py:279
#, python-format
msgid "Processing local manifest %s (%s)"
msgstr "Обробка локального маніфесту %s (%s)"

#: ../duplicity/dup_collections.py:294
msgid ""
"Error processing remote file ({os.fsdecode(remote_file)}): "
"{util.uexc(message)}"
msgstr ""

#: ../duplicity/dup_collections.py:296
msgid ""
"Processing remote file {os.fsdecode(remote_file)} ({len(remote_file_buffer)})"
msgstr ""

#: ../duplicity/dup_collections.py:314
msgid "No Jsonstat file found, return enmty."
msgstr ""

#: ../duplicity/dup_collections.py:407
msgid "Preferring Backupset over previous one!"
msgstr "Перевага набору резервних копій замість попереднього!"

#: ../duplicity/dup_collections.py:411
#, python-format
msgid "Ignoring incremental Backupset (start_time: %s; needed: %s)"
msgstr ""
"Ігнорування покрокового набору резервних копій (час_початку: %s; необхідно: "
"%s)"

#: ../duplicity/dup_collections.py:420
#, python-format
msgid "Added incremental Backupset (start_time: %s / end_time: %s)"
msgstr ""
"Додано покроковий набір резервних копій (час_початку: %s / час_кінця: %s)"

#: ../duplicity/dup_collections.py:493
msgid "Chain start time: "
msgstr "Ланцюжок почато: "

#: ../duplicity/dup_collections.py:494
msgid "Chain end time: "
msgstr "Ланцюжок закінчено: "

#: ../duplicity/dup_collections.py:495
#, python-format
msgid "Number of contained backup sets: %d"
msgstr "Кількість наборів резервних копій, що містяться: %d"

#: ../duplicity/dup_collections.py:496
#, python-format
msgid "Total number of contained volumes: %d"
msgstr "Загальне число томів, що містяться: %d"

#: ../duplicity/dup_collections.py:497 ../duplicity/dup_collections.py:1311
msgid "Type of backup set:"
msgstr "Тип набору резервних копій:"

#: ../duplicity/dup_collections.py:497 ../duplicity/dup_collections.py:1311
msgid "Time:"
msgstr "Час:"

#: ../duplicity/dup_collections.py:497
msgid "Num volumes:"
msgstr "Число томів:"

#: ../duplicity/dup_collections.py:502 ../duplicity/dup_collections.py:1318
msgid "Full"
msgstr "Повна"

#: ../duplicity/dup_collections.py:505 ../duplicity/dup_collections.py:1320
msgid "Incremental"
msgstr "Покрокове"

#: ../duplicity/dup_collections.py:566
msgid "local"
msgstr "локальна"

#: ../duplicity/dup_collections.py:729
msgid "Collection Status"
msgstr "Стан збору"

#: ../duplicity/dup_collections.py:731
#, python-format
msgid "Connecting with backend: %s"
msgstr "З’єднання з внутрішнім інтерфейсом: %s"

#: ../duplicity/dup_collections.py:732
#, python-format
msgid "Archive dir: %s"
msgstr "Тека архіву: %s"

#: ../duplicity/dup_collections.py:735
#, python-format
msgid "Found %d secondary backup chain(s)."
msgstr ""

#: ../duplicity/dup_collections.py:737
#, python-format
msgid "Secondary chain %d of %d:"
msgstr "Вторинний ланцюжок %d з %d:"

#: ../duplicity/dup_collections.py:742
msgid "Found primary backup chain with matching signature chain:"
msgstr ""
"Знайдено первинний ланцюжок резервних копій з відповідним ланцюжком підпису:"

#: ../duplicity/dup_collections.py:745
msgid "No backup chains with active signatures found"
msgstr "Відсутні ланцюжки ланцюжок резервних копій з активними підписами"

#: ../duplicity/dup_collections.py:748
#, python-format
msgid "Also found %d backup set(s) not part of any chain,"
msgstr ""

#: ../duplicity/dup_collections.py:749
#, python-format
msgid "and %d incomplete backup set(s)."
msgstr ""

#. "cleanup" is a hard-coded command, so do not translate it
#: ../duplicity/dup_collections.py:751
msgid ""
"These may be deleted by running duplicity with the \"cleanup\" command."
msgstr ""
"Це може бути вилучено за допомогою запуску duplicity з командою «cleanup»."

#: ../duplicity/dup_collections.py:753
msgid "No orphaned or incomplete backup sets found."
msgstr "Відсутні ізольовані або неповні набори резервних копій."

#: ../duplicity/dup_collections.py:769
#, python-format
msgid "%d file(s) exists on backend"
msgstr ""

#: ../duplicity/dup_collections.py:775
#, python-format
msgid "%d file exists in cache"
msgid_plural "%d files exist in cache"
msgstr[0] "%d файл існує у тимчасових файлах"
msgstr[1] "%d файли існує у тимчасових файлах"
msgstr[2] "%d файлів існує у тимчасових файлах"

#: ../duplicity/dup_collections.py:834
msgid ""
"Warning, discarding last backup set, because of missing signature file."
msgstr ""
"Увага, відкликано останній набір резервних копій, у зв’язку з відсутністю "
"файлу підпису."

#: ../duplicity/dup_collections.py:857
msgid "Warning, found the following local orphaned signature file(s):"
msgstr ""

#: ../duplicity/dup_collections.py:865
msgid "Warning, found the following remote orphaned signature file(s):"
msgstr ""

#: ../duplicity/dup_collections.py:873
msgid "Warning, found signatures but no corresponding backup files"
msgstr "Увага, знайдено підписи, які не відповідають файлам резервної копії"

#: ../duplicity/dup_collections.py:879
msgid ""
"Warning, found incomplete backup sets, probably left from aborted session"
msgstr ""
"Увага, знайдено неповні набори резервних копій, можливо вони залишилися від "
"перерваного сеансу"

#: ../duplicity/dup_collections.py:885
msgid "Warning, found the following orphaned backup file(s):"
msgstr ""

#: ../duplicity/dup_collections.py:900
#, python-format
msgid "Extracting backup chains from list of files: %s"
msgstr "Видобування ланцюжків резервної копії зі списку файлів: %s"

#: ../duplicity/dup_collections.py:911
#, python-format
msgid "File %s is part of known set"
msgstr "Файл %s є частиною відомого набору"

#: ../duplicity/dup_collections.py:914
#, python-format
msgid "File %s is not part of a known set; creating new set"
msgstr "Файл %s не є частиною відомого набору; створюється новий набір"

#: ../duplicity/dup_collections.py:919
#, python-format
msgid "Ignoring file (rejected by backup set) '%s'"
msgstr "Ігнорування файлу (відхилено набором резервних копій) '%s'"

#: ../duplicity/dup_collections.py:935
#, python-format
msgid "Found backup chain %s"
msgstr "Знайдено ланцюжок резервних копій %s"

#: ../duplicity/dup_collections.py:940
#, python-format
msgid "Added set %s to pre-existing chain %s"
msgstr "Додавання набору %s для раніше існуючого ланцюжка %s"

#: ../duplicity/dup_collections.py:943
#, python-format
msgid "Found orphaned set %s"
msgstr "Знайдено ізольований набір %s"

#: ../duplicity/dup_collections.py:1091
#, python-format
msgid ""
"No signature chain for the requested time. Using oldest available chain, "
"starting at time %s."
msgstr ""
"Немає ланцюжка підписів для запитуваного часу. Використовується найстаріший "
"доступний ланцюжок, починаючи з часу %s."

#: ../duplicity/dup_collections.py:1309
#, python-format
msgid "File: %s"
msgstr "Файл: %s"

#: ../duplicity/dup_collections.py:1310
#, python-format
msgid "Total number of backup: %d"
msgstr "Загальна кількість резервних копій: %d"

#: ../duplicity/dup_collections.py:1311 ../duplicity/dup_collections.py:1347
msgid "Type of file change:"
msgstr "Тип змінення файлу:"

#: ../duplicity/dup_collections.py:1345
#, python-format
msgid " Backup set time: %s"
msgstr ""

#: ../duplicity/dup_collections.py:1346
#, python-format
msgid "Total number of changes: %d"
msgstr ""

#: ../duplicity/dup_collections.py:1347
msgid "File:"
msgstr ""

#: ../duplicity/patchdir.py:72 ../duplicity/patchdir.py:79
#, python-format
msgid "Patching %s"
msgstr "Внесення змін у %s"

#: ../duplicity/patchdir.py:547
#, python-format
msgid "Error '%s' patching %s"
msgstr "Помилка «%s» внесення змін «%s»"

#: ../duplicity/patchdir.py:624
#, python-format
msgid "Writing %s of type %s"
msgstr "Запис %s типу %s"

#: ../duplicity/selection.py:115
#, python-format
msgid "Skipping socket %s"
msgstr "Пропуск сокету %s"

#: ../duplicity/selection.py:121
#, python-format
msgid "Error initializing file %s"
msgstr "Помилка ініціалізації файлу %s"

#: ../duplicity/selection.py:127 ../duplicity/selection.py:167
#: ../duplicity/selection.py:615
#, python-format
msgid "Error accessing possibly locked file %s"
msgstr "Помилка доступу до можливо заблокованого файлу %s"

#: ../duplicity/selection.py:182
#, python-format
msgid "Warning: base %s doesn't exist, continuing"
msgstr "Увага: база %s не існує, виконується продовження"

#: ../duplicity/selection.py:184 ../duplicity/selection.py:205
#: ../duplicity/selection.py:208
#, python-format
msgid "Selecting %s"
msgstr "Вибір %s"

#: ../duplicity/selection.py:263
#, python-format
msgid ""
"                The last file selection option is the filter option %s, "
"which will have no\n"
"                effect as there are no subsequent file selection options. "
"Exiting because\n"
"                this probably isn't what you meant."
msgstr ""

#: ../duplicity/selection.py:278
#, python-format
msgid ""
"                Only these filter mode options were specified:\n"
"                    %s\n"
"                Case sensitive globbing is the default behaviour and so this "
"has no effect.\n"
"                Exiting because this probably isn't what you meant."
msgstr ""

#: ../duplicity/selection.py:346
#, python-format
msgid ""
"                Fatal Error: The file specification\n"
"                    %s\n"
"                cannot match any files in the base directory\n"
"                    %s\n"
"                Useful file specifications begin with the base directory or "
"some\n"
"                pattern (such as '**') which matches the base directory."
msgstr ""

#: ../duplicity/selection.py:360
#, python-format
msgid ""
"Fatal Error while processing expression\n"
"%s"
msgstr ""
"Фатальна помилка при обробці виразу\n"
"%s"

#: ../duplicity/selection.py:378
#, python-format
msgid "Reading files to backup from list %s"
msgstr ""

#: ../duplicity/selection.py:403
#, python-format
msgid ""
"                Files-from list contains the absolute path:\n"
"                    %s\n"
"                All paths specified in a files-from list must be given "
"relative to the backup\n"
"                source path."
msgstr ""

#: ../duplicity/selection.py:418
msgid ""
"                Files-from list specified which contains no files, the "
"backup will be empty as\n"
"                a result. Exiting as this probably isn't what you meant,"
msgstr ""

#: ../duplicity/selection.py:435
#, python-format
msgid ""
"                Last selection expression:\n"
"                    %s\n"
"                only specifies that files be included.  Because the default "
"is to\n"
"                include all files, the expression is redundant.  Exiting "
"because this\n"
"                probably isn't what you meant."
msgstr ""

#: ../duplicity/selection.py:497
#, python-format
msgid "Reading %s filelist %s"
msgstr ""

#: ../duplicity/selection.py:538
#, python-format
msgid "Error compiling regular expression %s"
msgstr "Помилка компілювання регулярного виразу %s"

#: ../duplicity/lazy.py:349
#, python-format
msgid "Warning: oldindex %s >= newindex %s"
msgstr "Увага: старий індекс %s >= нового індексу %s"

#: ../duplicity/lazy.py:424
#, python-format
msgid "Error '%s' processing %s"
msgstr "Помилка «%s» при обробці %s"

#: ../duplicity/lazy.py:436
#, python-format
msgid "Skipping %s because of previous error"
msgstr "Пропуск %s внаслідок попередньої помилки"

#: ../duplicity/path.py:109
#, python-format
msgid "Warning: %s invalid devnums (0x%X), treating as (0, 0)."
msgstr ""
"Попередження: %s неприпустимих devnums (0x%X), трактуються як (0, 0)."

#: ../duplicity/path.py:239 ../duplicity/path.py:299
#, python-format
msgid "Warning: %s has negative mtime, treating as 0."
msgstr "Увага: у %s від’ємне mtime, приймається рівним 0."

#: ../duplicity/path.py:372
#, python-format
msgid "New file %s"
msgstr "Новий файл %s"

#: ../duplicity/path.py:375
#, python-format
msgid "File %s is missing"
msgstr "Файл %s відсутній"

#: ../duplicity/path.py:378
#, python-format
msgid "File %%s has type %s, expected %s"
msgstr "Файл %%s відноситься до типу %s, а очікувався %s"

#: ../duplicity/path.py:383 ../duplicity/path.py:412
#, python-format
msgid "File %%s has permissions %s, expected %s"
msgstr "Файл %%s має дозволи %s, а очікувалося %s"

#: ../duplicity/path.py:389
#, python-format
msgid "File %%s has mtime %s, expected %s"
msgstr "Файл %%s має mtime %s, а очікувалося %s"

#: ../duplicity/path.py:400
#, python-format
msgid "Data for file %s is different"
msgstr "Дані для файлу %s відмінні"

#: ../duplicity/path.py:408
#, python-format
msgid "Symlink %%s points to %s, expected %s"
msgstr "Символічне посилання %%s вказує на %s, а очікувалося %s"

#: ../duplicity/path.py:415
#, python-format
msgid "Device file %%s has numbers %s, expected %s"
msgstr "Файл пристрою %%s містить номери %s, а очікувалося %s"

#: ../duplicity/path.py:605
#, python-format
msgid "Making directory %s"
msgstr "Створюється каталог %s"

#: ../duplicity/path.py:615
#, python-format
msgid "Deleting %s"
msgstr "Вилучається %s"

#: ../duplicity/path.py:624
#, python-format
msgid "Touching %s"
msgstr "Зв’язатися %s"

#: ../duplicity/path.py:632
#, python-format
msgid "Deleting tree %s"
msgstr "Вилучення дерева %s"

#: ../duplicity/cli_util.py:48
msgid "Enter 'duplicity --help' for help screen."
msgstr "Уведіть «duplicity --help» для показу довідки."

#: ../duplicity/cli_util.py:127
msgid ""
"Running in 'ignore errors' mode due to --ignore-errors.\n"
"Please reconsider if this was not intended"
msgstr ""

#: ../duplicity/cli_util.py:139
msgid ""
"Use of the --asynchronous-upload option is experimental and not safe for "
"production! There are reported cases of undetected data loss during upload. "
"Be aware and periodically verify your backups to be safe."
msgstr ""

#: ../duplicity/cli_util.py:152
msgid "'{val}' is not an int: {str(e)}"
msgstr ""

#: ../duplicity/cli_util.py:166
#, python-brace-format
msgid "'{val} is not a single character."
msgstr ""

#: ../duplicity/cli_util.py:193
#, python-brace-format
msgid "Source should be pathname, not url.  Got '{val}' instead."
msgstr ""

#: ../duplicity/cli_util.py:195
#, python-brace-format
msgid "Argument source_path '{val}' does not exist."
msgstr ""

#: ../duplicity/cli_util.py:201
#, python-brace-format
msgid "Source should be url, not directory.  Got '{val}' instead."
msgstr ""

#: ../duplicity/cli_util.py:207
#, python-brace-format
msgid "Target should be directory, not url.  Got '{val}' instead."
msgstr ""

#: ../duplicity/cli_util.py:212
msgid "Unable to create target dir '{val}': {str(e)}"
msgstr ""

#: ../duplicity/cli_util.py:218
#, python-brace-format
msgid "Target should be url, not directory.  Got '{val}' instead."
msgstr ""

#: ../duplicity/cli_util.py:263
msgid ""
"Verbosity must be one of: digit [0-9], character [ewnid],\n"
"or word ['error', 'warning', 'notice', 'info', 'debug'].\n"
"The default is 3 (Notice).  It is strongly recommended\n"
"that verbosity level is set at 2 (Warning) or higher."
msgstr ""

#: ../duplicity/cli_util.py:399
#, python-brace-format
msgid ""
"Specified archive directory '{archive_dir_path.uc_name}' is not a directory"
msgstr ""

#: ../duplicity/cli_util.py:408
msgid ""
"Encrypt key should be an 8, 16, or 40 character hex string, like "
"'AA0E73D2'.\n"
msgstr ""

#: ../duplicity/cli_util.py:428
msgid ""
"Hidden dncrypt key should be an 8, 16, or 40 character hex string, like "
"'AA0E73D2'.\n"
msgstr ""

#: ../duplicity/cli_util.py:442
msgid ""
"Sign key should be an 8, 16, or 40 character hex string, like 'AA0E73D2'.\n"
msgstr ""

#: ../duplicity/argparse311.py:291
msgid "usage: "
msgstr ""

#: ../duplicity/argparse311.py:761
#, python-format
msgid "argument %(argument_name)s: %(message)s"
msgstr ""

#: ../duplicity/argparse311.py:870
msgid ".__call__() not defined"
msgstr ""

#: ../duplicity/argparse311.py:1115
#, python-format
msgid "conflicting subparser: %s"
msgstr ""

#: ../duplicity/argparse311.py:1118
#, python-format
msgid "conflicting subparser alias: %s"
msgstr ""

#: ../duplicity/argparse311.py:1152
#, python-format
msgid "unknown parser %(parser_name)r (choices: %(choices)s)"
msgstr ""

#: ../duplicity/argparse311.py:1215
#, python-format
msgid "argument \"-\" with mode %r"
msgstr ""

#: ../duplicity/argparse311.py:1223
#, python-format
msgid "can't open '%(filename)s': %(error)s"
msgstr ""

#: ../duplicity/argparse311.py:1427
#, python-format
msgid "cannot merge actions - two groups are named %r"
msgstr ""

#: ../duplicity/argparse311.py:1462
msgid "'required' is an invalid argument for positionals"
msgstr ""

#: ../duplicity/argparse311.py:1483
#, python-format
msgid ""
"invalid option string %(option)r: must start with a character "
"%(prefix_chars)r"
msgstr ""

#: ../duplicity/argparse311.py:1500
#, python-format
msgid "dest= is required for options like %r"
msgstr ""

#: ../duplicity/argparse311.py:1517
#, python-format
msgid "invalid conflict_resolution value: %r"
msgstr ""

#: ../duplicity/argparse311.py:1534
#, python-format
msgid "conflicting option string: %s"
msgid_plural "conflicting option strings: %s"
msgstr[0] ""
msgstr[1] ""

#: ../duplicity/argparse311.py:1595
msgid "mutually exclusive arguments must be optional"
msgstr ""

#: ../duplicity/argparse311.py:1670
msgid "positional arguments"
msgstr ""

#: ../duplicity/argparse311.py:1689
msgid "show this help message and exit"
msgstr ""

#: ../duplicity/argparse311.py:1721
msgid "cannot have multiple subparser arguments"
msgstr ""

#: ../duplicity/argparse311.py:1769 ../duplicity/argparse311.py:2264
#, python-format
msgid "unrecognized arguments: %s"
msgstr ""

#: ../duplicity/argparse311.py:1868
#, python-format
msgid "not allowed with argument %s"
msgstr ""

#: ../duplicity/argparse311.py:1912 ../duplicity/argparse311.py:1926
#, python-format
msgid "ignored explicit argument %r"
msgstr ""

#: ../duplicity/argparse311.py:2030
#, python-format
msgid "the following arguments are required: %s"
msgstr ""

#: ../duplicity/argparse311.py:2042
#, python-format
msgid "one of the arguments %s is required"
msgstr ""

#: ../duplicity/argparse311.py:2083
msgid "expected one argument"
msgstr ""

#: ../duplicity/argparse311.py:2084
msgid "expected at most one argument"
msgstr ""

#: ../duplicity/argparse311.py:2085
msgid "expected at least one argument"
msgstr ""

#: ../duplicity/argparse311.py:2089
#, python-format
msgid "expected %s argument"
msgid_plural "expected %s arguments"
msgstr[0] ""
msgstr[1] ""

#: ../duplicity/argparse311.py:2143
#, python-format
msgid "ambiguous option: %(option)s could match %(matches)s"
msgstr ""

#: ../duplicity/argparse311.py:2207
#, python-format
msgid "unexpected option string: %s"
msgstr ""

#: ../duplicity/argparse311.py:2402
#, python-format
msgid "%r is not callable"
msgstr ""

#: ../duplicity/argparse311.py:2419
#, python-format
msgid "invalid %(type)s value: %(value)r"
msgstr ""

#: ../duplicity/argparse311.py:2429
#, python-format
msgid "invalid choice: %(value)r (choose from %(choices)s)"
msgstr ""

#: ../duplicity/argparse311.py:2505
#, python-format
msgid "%(prog)s: error: %(message)s\n"
msgstr ""

#~ msgid "GnuPG passphrase for signing key:"
#~ msgstr "Кодова фраза GnuPG для підписуючого ключа:"

#, python-format
#~ msgid "Cleaning up previous partial %s backup set, restarting."
#~ msgstr ""
#~ "Очищення попереднього часткового %s набору резервного копіювання, "
#~ "виконується перезапуск."

#, python-format
#~ msgid "Last %s backup left a partial set, restarting."
#~ msgstr ""
#~ "Остання %s резервна копія залишила частковий набір, виконується перезапуск."

#~ msgid "Last full backup date:"
#~ msgstr "Час останньої повної резервної копії:"

#~ msgid "running task synchronously (asynchronicity disabled)"
#~ msgstr "виконання завдання синхронно (асинхронність вимкнено)"

#~ msgid "inserting barrier"
#~ msgstr "вставка бар’єру"

#~ msgid "task completed successfully"
#~ msgstr "завдання успішно закінчено"

#, python-format
#~ msgid "instantiating at concurrency %d"
#~ msgstr "паралельне створення %d"

#, python-format
#~ msgid "active workers = %d"
#~ msgstr "активні обробники = %d"

#~ msgid ""
#~ "a previously scheduled task has failed; propagating the result immediately"
#~ msgstr ""
#~ "не вдалося виконати заплановане раніше завдання; виконується миттєве "
#~ "розповсюдження результату"

#, python-format
#~ msgid "Command line error: %s"
#~ msgstr "Помилка у командному рядку: %s"

#, python-format
#~ msgid "Using backup name: %s"
#~ msgstr "Використання назви резервної копії: %s"

#, python-format
#~ msgid "Using archive dir: %s"
#~ msgstr "Використання каталогу архіву: %s"

#~ msgid "Commands:"
#~ msgstr "Команди:"

#, python-format
#~ msgid "Command line warning: %s"
#~ msgstr "Попередження командного рядка: %s"

#, python-format
#~ msgid ""
#~ "Restore destination directory %s already exists.\n"
#~ "Will not overwrite."
#~ msgstr ""
#~ "Каталог у який призначене відновлення %s вже існує.\n"
#~ "Заміну не буде проведено."

#, python-format
#~ msgid "Backup source directory %s does not exist."
#~ msgstr "Теки джерела резервної копії %s не існує."

#~ msgid "Main action: "
#~ msgstr "Основна дія: "

#, python-format
#~ msgid ""
#~ "Last selection expression:\n"
#~ "    %s\n"
#~ "only specifies that files be included.  Because the default is to\n"
#~ "include all files, the expression is redundant.  Exiting because this\n"
#~ "probably isn't what you meant."
#~ msgstr ""
#~ "Вираз останнього виділення:\n"
#~ "    %s\n"
#~ "лише вказує на те, що файли буде включено. Оскільки\n"
#~ "типово включаються усі файли, отже вираз надлишковий.\n"
#~ "Виконання виходу, оскільки можливо, що ймовірно, це не те, що ви мали на "
#~ "увазі."

#, python-format
#~ msgid ""
#~ "Fatal Error: The file specification\n"
#~ "    %s\n"
#~ "cannot match any files in the base directory\n"
#~ "    %s\n"
#~ "Useful file specifications begin with the base directory or some\n"
#~ "pattern (such as '**') which matches the base directory."
#~ msgstr ""
#~ "Фатальна помилка: Специфікація файлу\n"
#~ "    %s\n"
#~ "не може відповідати будь-яким файлам у базовому каталозі\n"
#~ "    %s\n"
#~ "Корисні специфікації файлу починаються з базового каталогу або\n"
#~ "маски (наприклад '**'), яка відповідає базовому каталогу."

#~ msgid "scheduling task for asynchronous execution"
#~ msgstr "планування завдання для асинхронного виконання"

#~ msgid ""
#~ "Selection options --exclude/--include\n"
#~ "currently work only when backing up,not restoring."
#~ msgstr ""
#~ "Параметри вибору --exclude/--include\n"
#~ "на даний час працюють лише для резервного копіювання, не для відновлення."

#, python-format
#~ msgid ""
#~ "Fatal Error: Backup source directory has changed.\n"
#~ "Current directory: %s\n"
#~ "Previous directory: %s"
#~ msgstr ""
#~ "Фатальна помилка: Початковий каталог резервної копії було змінено.\n"
#~ "Поточний каталог: %s\n"
#~ "Попередній каталог: %s"

#, python-format
#~ msgid "File %s already exists, will not overwrite."
#~ msgstr "Файл %s вже існує, його не буде перезаписано."

#~ msgid ""
#~ "Option '--ssl-cacert-path' is not supported with python 2.7.8 and below."
#~ msgstr "Параметр «--ssl-cacert-path» не підтримується python 2.7.8 і нижче."

#, python-format
#~ msgid "GPG process %d terminated before wait()"
#~ msgstr "Процес GPG %d припинився до виклику wait()"

#, python-format
#~ msgid "Processing remote manifest %s (%s)"
#~ msgstr "Обробка віддаленого маніфесту %s (%s)"

#~ msgid ""
#~ "\n"
#~ "PYTHONOPTIMIZE in the environment causes duplicity to fail to\n"
#~ "recognize its own backups.  Please remove PYTHONOPTIMIZE from\n"
#~ "the environment and rerun the backup.\n"
#~ "\n"
#~ "See https://bugs.launchpad.net/duplicity/+bug/931175\n"
#~ msgstr ""
#~ "\n"
#~ "PYTHONOPTIMIZE у середовищі призводить до збою duplicity\n"
#~ "під час розпізнання власних резервних копій.  Прохання видалити\n"
#~ "PYTHONOPTIMIZE з середовища і перезапустити створення\n"
#~ "резервної копії.\n"
#~ "\n"
#~ "Див. https://bugs.launchpad.net/duplicity/+bug/931175\n"

#, python-format
#~ msgid ""
#~ "Running in 'ignore errors' mode due to %s; please re-consider if this was "
#~ "not intended"
#~ msgstr ""
#~ "Виконання у режимі «ігнорування помилок» у зв’язку з %s; будь-ласка, "
#~ "перегляньте рішення, якщо це не було наміром"

#~ msgid "regular_expression"
#~ msgstr "регулярний_вираз"

#~ msgid "pyrax|cloudfiles"
#~ msgstr "pyrax|хмарніфайли"

#~ msgid "source_dir"
#~ msgstr "вихідний_каталог"

#, python-format
#~ msgid "GPG binary is %s, version %s"
#~ msgstr "Двійковий файл GPG — %s, версія %s"

#, python-format
#~ msgid ""
#~ "Specified archive directory '%s' does not exist, or is not a directory"
#~ msgstr "Вказана тека архіву «%s» не існує або не є текою"

#, python-format
#~ msgid ""
#~ "Sign key should be an 8, 16 alt. 40 character hex string, like 'AA0E73D2'.\n"
#~ "Received '%s' instead."
#~ msgstr ""
#~ "Ключ підпису повинен бути 8, 16 чи альтернативно 40-символьний "
#~ "шістнадцятковий рядок, наприклад «AA0E73D2». Натомість отримано «%s»."

#, python-format
#~ msgid "Verify directory %s does not exist"
#~ msgstr "Переконайтеся, що тека %s не існує"

#, python-format
#~ msgid ""
#~ "Bad URL '%s'.\n"
#~ "Examples of URL strings are \"scp://user@host.net:1234/path\" and\n"
#~ "\"file:///usr/local\".  See the man page for more information."
#~ msgstr ""
#~ "Неприпустиме адресне посилання URL «%s».\n"
#~ "Наприклад: «scp://user@host.net:1234/path» та\n"
#~ "«file:///usr/local». Для отримання додаткової інформації зверніться до "
#~ "керівництва (man)."

#~ msgid "Difference found:"
#~ msgstr "Знайдено відмінність:"

#~ msgid "Threading not available -- zombie processes may appear"
#~ msgstr "Розгалуження недоступне — можуть з'явитися зомбі-процеси"

#, python-format
#~ msgid "Exception during list of %s: %s"
#~ msgstr "Помилка під час перелічення %s: %s"

#, python-format
#~ msgid "Error opening file %s"
#~ msgstr "Помилка відкривання файлу «%s»"
